### ISSUE TITLE
No Octopi

### ISSUE THREAD

**Issue by TxBillbr** [markniu/Bed_Distance_sensor#10]
Enhancement request.
Mark, many Klipper users do not use Octopi for Klipper interface. It would be more acceptable if Instructions were also provided for installation on Fluidd, Mainsail, or other more widely used clients. Many klipper add-ons use Kiauh for installing, updating, and removing software from the Klipper environment.

**Comment by markniu** [comment]
I agree that if there are instructions for fulidd and others are better. actually, there are no different to install BDsensor in Octopi or Fluidd while using klipper, because the config and source code are changed only in klipper side.  the other reason is time limited for me to do that recently.

**Comment by markniu** [comment]
Hi, Thanks for feedback this, just replace the klipper code by git clone again.
```
cd ~ 
mv klipper klipper_bak
git clone https://github.com/markniu/klipper-for-pull.git
mv klipper-for-pull/ klipper
cd ~/klipper/
make menuconfig
```
https://github.com/markniu/Bed_Distance_sensor/wiki/Installing-for-Klipper
