### ISSUE TITLE
Internal error on command:"G28" while homing Z axis

### ISSUE THREAD

**Issue by BUGBEAR7** [markniu/Bed_Distance_sensor#103]
Hello , 

Recently installed on my Enderwire , after calibration Z axis is not homing gets Internal error on command:"G28"
Here is the [klippy.log](https://github.com/markniu/Bed_Distance_sensor/files/14481264/klippy.log)
I am not sure what I am doing wrong , Sensor is v1.2

**Comment by markniu** [comment]
the reason is the aliases board pins, please use the PB8 PB9 instead of PROBE_2 PROBE_1

**Comment by BUGBEAR7** [comment]
Thanks for that , it fixed the issue.
