### ISSUE TITLE
Weird Motor Sound at Homing with 3 Z-Motors with 1 driver every motor

### ISSUE THREAD

**Issue by RicardoHipp** [markniu/Bed_Distance_sensor#108]
it works, but on z homing the motors make a weird and loud sound.

https://www.youtube.com/watch?v=t8_eU9_tqEI
the first 10 seconds its normally z moving, then z homing, you can hear the different

I use klipper  v0.12.0-125

i used 3 z axis motors.

with my CR touch everything is fine only changing to BDSensor makes a weird sound at homing in Z, but not on normal moving.

i used 3 z axis motors with one driver every motor

I think it's a problem because while the Z axis is moving, the sensor is always measuring, but it's really very loud.

[config-20240318-225751.zip](https://github.com/markniu/Bed_Distance_sensor/files/14642925/config-20240318-225751.zip)

**Comment by markniu** [comment]
this happens in some multi z axis printers, the MCU control the multi z axis driver but at same time need to read the bdsensor at very high frequency. 
there are 2 solutions:
1: connect the BDsensor to the different controller, e.g. raspberryPi GPIO or the CAN module.
2: upgrade the firmware  of BDsensor to the latest version that will let the bdsensor works as a switch sensor while homing.
[ V1.2c](https://github.com/markniu/Bed_Distance_sensor/wiki/Flash-BDsensor(stm32)-firmware)

what's your bdsensor firmware version?  you can check the firmware of BDsensor by M102 S-1

**Comment by RicardoHipp** [comment]
Thanks, I flashed the new firmware and now i works.
