### ISSUE TITLE
Question about updating to new firmware version

### ISSUE THREAD

**Issue by Carontes** [markniu/Bed_Distance_sensor#109]
My bed sensor has version 1.1, I would like to update at version 1.3 but I don't understand if I need to have a new version of the bed sensor that came with version 1.2 already preinstalled or if I can update my bed sensor anyway? Do I always have to have the latest version of the firmware before flashing the new one or can I update from version 1 to version 3  jumping version 2, for example? Thank you

**Comment by markniu** [comment]
Hello, there are only 3 hardware version: V1.0, V1.1, V1.3. but the firmware version inside are V1.0, V1.1, V1.2
the V1.0 and V1.1 use the STC as its MCU, V1.3 use the STM32 as its MCU, so there are 2 latest firmware V1.1b and V1.2c for the STC and STM32. https://github.com/markniu/Bed_Distance_sensor/tree/new/hex
if you find the nozzle crash the bed sometimes while homing, you can flash it to the latest firmware, else no need to flash to the latest firmware.  
![image](https://github.com/markniu/Bed_Distance_sensor/assets/13879340/a4da0886-53b7-4946-a3c3-b2cc1b7c8489)

**Comment by Carontes** [comment]
I tried to follow [this](https://github.com/markniu/Bed_Distance_sensor/wiki/Flash-BDsensor(V1.1)-firmware) guide, I've used the wires included in the box with the bed sensor to connect it to the TTL Serial: Moved the jumper to connect 5V and VCC instead of 3V3, but when I click Download/Program nothing happens and the only sentence I see is `Checking target MCU ... `. I know the TTL works because I've used it to flash Openwrt on some routers, so probably I'm doing something wrong

**Comment by markniu** [comment]
after click the Download button,  reboot the bdsensor by cutting power and then power up.

**Comment by Carontes** [comment]
![IMG_20240328_181211](https://github.com/markniu/Bed_Distance_sensor/assets/762290/aafe3eee-a054-463a-853d-43cf76810510)
![Screenshot 2024-03-28 181420](https://github.com/markniu/Bed_Distance_sensor/assets/762290/15554381-ba40-4233-a3bd-a9989f7df991)
The bed sensor is not connected to the printer but directly to the TTL, so I don't know how to make power off and on without unplug the wires from the TTL

**Comment by markniu** [comment]
there is a mistake  :),  we can't flash the sensor via the white connector on the sensor. 
we can just unplug/plug the 5v cable to reboot the BDsensor.

**Comment by Carontes** [comment]
So I do I have to set the wires? I knew it was my mistake. Sorry but I'm not familiar with it

**Comment by markniu** [comment]
Need to solder wires to bdsensor, and plug the wires to the TTL Serial module board.
reboot the bd sensor by unplug and plug the 5V wire into TTL serial module board after clicking the download button. 
![image](https://github.com/markniu/Bed_Distance_sensor/assets/13879340/16ec3668-1a34-4263-94a8-4203703ecd4e)

**Comment by Carontes** [comment]
I might be stupid and probably I am, but I see no points where I can solder wires on the bdsensor

![IMG_20240329_105359](https://github.com/markniu/Bed_Distance_sensor/assets/762290/ca347303-995b-42c2-8cf4-c40e2485c170)
![IMG_20240329_105440](https://github.com/markniu/Bed_Distance_sensor/assets/762290/25bdd6fc-94a3-4ab0-8ad5-f67a885c6a57)

**Comment by markniu** [comment]
this is the first batch of v1.1 and there are no solder points outside. please send me your order number from pandapi3d.com, I would like to send you the latest V1.3.

**Comment by Carontes** [comment]
Order No. 10540
Placed on Nov 17, 2023
Thank you for your help and time

**Comment by ptegler** [comment]
same boat.... have never been able to use mine since purchasing back in 2002!  (need a usable unit!)


![bd_sensor_purchase-info](https://github.com/markniu/Bed_Distance_sensor/assets/5613400/f85f9ca1-f47d-4f02-a4d9-31c37f581601)

**Comment by markniu** [comment]
thanks for purchase the early version, we will send you new one those days.
> same boat.... have never been able to use mine since purchasing back in 2002! (need a usable unit!)
>

**Comment by ptegler** [comment]
> thanks for purchase the early version, we will send you new one those days.
> 
> > same boat.... have never been able to use mine since purchasing back in 2002! (need a usable unit!)

now THAT would be fanTASTIC!  thank you @markniu

**Comment by gerkow** [comment]
BDsensorVer:V1.0 pandapi3d.com ,switch_mode=0,collision_homing=0,collision_cal=0
Order No. 10365	Placed on Apr 9, 2023
No Update possible?

**Comment by Raabi91** [comment]
same for me have the first batch desing cannot flash the sensor

![Screenshot 2024-04-01 124810](https://github.com/markniu/Bed_Distance_sensor/assets/38133278/5572878e-d067-414e-89b0-aed3a459238f)

**Comment by gerkow** [comment]
I have V1.0 so ordered a SensorM 
cant wait 2 try collision_calibrate n homing.

**Comment by markniu** [comment]
thanks for the first batch,  the track number will be send with email.

> same for me have the first batch desing cannot flash the sensor
>

**Comment by markniu** [comment]
> I have V1.0 so ordered a SensorM cant wait 2 try collision_calibrate n homing.

got it, thank you very much, will send one more coil&wire with it.

the collision sensing is very useful and I will apply this to fix the stable problem in the real time leveling future.

**Comment by terri1769** [comment]
I'm running into this as well.  My last order was 10224, but I'm not sure if that's for this particular one.  It seems like there was a problem purchasing at one point and you directed me to anther site.
