### ISSUE TITLE
Cant flash latest firmware to v1.1

### ISSUE THREAD

**Issue by Kowy54** [markniu/Bed_Distance_sensor#112]
![image](https://github.com/markniu/Bed_Distance_sensor/assets/31593455/bd5f116f-30e9-475b-851f-a409eee813e5)
I have version 1.1 soldered to USB-TTL as is shown on image on wiki.
cant flash latest firmware from github. No output in COM window :/

**Comment by Kowy54** [comment]
![image](https://github.com/markniu/Bed_Distance_sensor/assets/31593455/861b4244-5367-4947-82bb-979be2fddc90)
This error will appear everytime when i run STC-ISP

**Comment by markniu** [comment]
did you reboot the bdsensor by cut off the 5v power and then on after click the download button? 
it needs to be reboot after click the download button.

**Comment by Kowy54** [comment]
Problem solved via help on facebook
