### ISSUE TITLE
40mm mount too high, 42mm mount too close

### ISSUE THREAD

**Issue by m3hrz4d** [markniu/Bed_Distance_sensor#115]
Would you mind making a 41mm mount? It seems that no matter what adjustments I make, with the 40mm mount, after calibration it reports being too high, and with the 42mm mount, it reports too close.

**Comment by markniu** [comment]
I just shared this on the tinkercad which is very easy to make a change, you can copy to your project and edit it. 
https://www.tinkercad.com/things/78VnoNvUNGg-bdsensormountbltouch/edit?returnTo=%2Fdashboard%2Fdesigns%2F3d&sharecode=7iTyqhPwZmxYlUY8KclD9hpphP839cwri4dkjo7g19g

**Comment by m3hrz4d** [comment]
I was able to get it figured out, thank you.
