### ISSUE TITLE
No data or corrupt data from BDsensor(), Please check connection

### ISSUE THREAD

**Issue by Townie-au** [markniu/Bed_Distance_sensor#117]
My setup was broken. So i had to reinstall everything.
I am having an issue with katapult not being able to access after flashing the ebb42.
So I have to flash klipper via stm32 programmer.
I connected bdsensor to the ebb42 when flashing klipper after installing bdsensor.
Now I get this error all the time.
Im using BD Sensor v1.
Everything was working including the bd sensor yesterday.
[klippy (27).log](https://github.com/markniu/Bed_Distance_sensor/files/15009506/klippy.27.log)
[printer.txt](https://github.com/markniu/Bed_Distance_sensor/files/15009519/printer.txt)

Ive checked continuity on the lead from the sensor to the board. OK
Canboard communicating via CAN0.
I just tried rolling back klipper to the previous version but no change.

Got katapult and klipper working still no chnage for bd sensor.

**Comment by Townie-au** [comment]
Ive checked continuity on the lead from the sensor to the board. OK
Canboard communicating via CAN0.

**Comment by Townie-au** [comment]
Is the bd sensor dead? Please help

**Comment by markniu** [comment]
you can test BDsensor with the gpio on the Pi.
for example:  https://github.com/markniu/Bed_Distance_sensor/issues/111#issuecomment-2046685001
connect the bdsensor to the gpio on the PI like gpio17 and gpio27.

[mcu host]
serial: /tmp/klipper_host_mcu

[BDsensor]
....
scl_pin: host:gpio17
sda_pin: host:gpio27

compile and flash firmware:
https://www.klipper3d.org/RPi_microcontroller.html

**Comment by Townie-au** [comment]
Ok. 
Got it working somewhat by flashing the beta firmware.
M102 s-1 returns nothing
M102 s-6 calibrates successfully
However when I go to home z I get "Bed Distance Sensor data error:10.24"
When I first started klipper up I got "collision_homing in printer.cfg invalid". So I commented out both collison homing lines.

**Comment by markniu** [comment]
Glad to hear it works again.

**Comment by Townie-au** [comment]
What about this Mark?
However when I go to home z I get "Bed Distance Sensor data error:10.24"

**Comment by markniu** [comment]
if M102 s-1 returns nothing or 10.24 means the same connection problem.

**Comment by markniu** [comment]
did you modify the cable before or just the software?

**Comment by Townie-au** [comment]
> did you modify the cable before or just the software?

Just the software.

**Comment by markniu** [comment]
for finding out what's the problem hardware or software, I think you can try the gpio on the pi.

**Comment by Townie-au** [comment]
> you can test BDsensor with the gpio on the Pi. for example: [#111 (comment)](https://github.com/markniu/Bed_Distance_sensor/issues/111#issuecomment-2046685001) connect the bdsensor to the gpio on the PI like gpio17 and gpio27.
> 
> [mcu host] serial: /tmp/klipper_host_mcu
> 
> [BDsensor] .... scl_pin: host:gpio17 sda_pin: host:gpio27
> 
> compile and flash firmware: https://www.klipper3d.org/RPi_microcontroller.html

host: Current version v0.12.0-124-g09a78c31
Up-to-date MCU(s):
<none>

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.

mcu 'host': Unknown command: I2C_BD_send

**Comment by Townie-au** [comment]
> > you can test BDsensor with the gpio on the Pi. for example: [#111 (comment)](https://github.com/markniu/Bed_Distance_sensor/issues/111#issuecomment-2046685001) connect the bdsensor to the gpio on the PI like gpio17 and gpio27.
> > [mcu host] serial: /tmp/klipper_host_mcu
> > [BDsensor] .... scl_pin: host:gpio17 sda_pin: host:gpio27
> > compile and flash firmware: https://www.klipper3d.org/RPi_microcontroller.html
> 
> host: Current version v0.12.0-124-g09a78c31 Up-to-date MCU(s):
> 
> Once the underlying issue is corrected, use the "RESTART" command to reload the config and restart the host software.
> 
> mcu 'host': Unknown command: I2C_BD_send

I connected the BD Sensor to my main board, recompiled and reflashed both EBB and M5P and got the same result.
I used probe port PC15 and PC13 on the BTT M5P. Couldnt use RPI. Would have to setup as secondary MCU.  :(

**Comment by markniu** [comment]
how about use the gpio in the EXP1? E.g. PB6 PB7

**Comment by Townie-au** [comment]
> how about use the gpio in the EXP1? E.g. PB6 PB7

Im going to try the RPI.

**Comment by Townie-au** [comment]
3.2 40 Pins GPIO
When Manta series motherboard work with CB1, 40 pins GPIO is a custom IO arrangement, as shown in the figure below, Pin 7 is CB1's "PC7", and Pin 11 is CB1's "PC14". The GPIO number of CB1 corresponds to (Px–PA)*32 + Pin
For example:
PC7 = (PC–PA)*32 + 7 = 2 * 32 + 7 = 71
PH10 = (PH–PA)*32 + 10 = 7 * 32 + 10 = 234
PC7 is numbered in Klipper as pin: host: gpio71, PH10 as pin: host: gpio234

WTH. Trying to make sense of this. I am using pin 11 and pin 15.

**Comment by Townie-au** [comment]
![CB1 GPIO](https://github.com/markniu/Bed_Distance_sensor/assets/26783417/9f07b9e5-6534-4fb6-bade-2da1371d1690)

**Comment by Townie-au** [comment]
OMG. Finally worked it out. GPIO78 and GPIO74
Same error on CB1 GPIO.

**Comment by markniu** [comment]
> OMG. Finally worked it out. GPIO78 and GPIO74 Same error on CB1 GPIO.

worked on RPI GPIO?

**Comment by Townie-au** [comment]
> > OMG. Finally worked it out. GPIO78 and GPIO74 Same error on CB1 GPIO.
> 
> worked on RPI GPIO?

No. Same error. No data or corrupt data from BDsensor(), Please check connection

**Comment by markniu** [comment]
what's the hardware version of bdsensor?

**Comment by Townie-au** [comment]
> what's the hardware version of bdsensor?

How do I tell?

**Comment by markniu** [comment]
there is a version text on the sensor on the other side of the white connector, like v1.3 or v1.1

**Comment by Townie-au** [comment]
v1.1

**Comment by markniu** [comment]
does the led on the sensor work? it will light on if it detects the metal else off.

**Comment by Townie-au** [comment]
> does the led on the sensor work? it will light on if it detects the metal else off.

Yes led lights up when metal is brought nearby

**Comment by markniu** [comment]
then from the hardware, we can only to find if the problem is from the dead mcu or the cable. 
do you have one more cable to replace the old one for the bdsensor?

**Comment by Townie-au** [comment]
> then from the hardware, we can only to find if the problem is from the dead mcu or the cable. do you have one more cable to replace the old one for the bdsensor?

No I dont. I checked the cable with the multimeter.

**Comment by markniu** [comment]
if you have a solder tool you can try to connect to a serial model, there will be many useful data output from the serial com port.

**Comment by Townie-au** [comment]
Do I need to open the case for that?

**Comment by markniu** [comment]
> Do I need to open the case for that?

No   
![image](https://github.com/markniu/Bed_Distance_sensor/assets/13879340/9a4ca530-af9a-43e6-b485-396ff923a255)

**Comment by Townie-au** [comment]
Would a ST LINK work?

**Comment by markniu** [comment]
> Would a ST LINK work?

No, the MCU on the v1.1 is not stm32

**Comment by Townie-au** [comment]
> > Would a ST LINK work?
> 
> No, the MCU on the v1.1 is not stm32

Would you be able to send me another bd sensor please?
Ill get the USB>UART converter and debug this one for you.

**Comment by markniu** [comment]
> > > Would a ST LINK work?
> > 
> > 
> > No, the MCU on the v1.1 is not stm32
> 
> Would you be able to send me another bd sensor please? Ill get the USB>UART converter and debug this one for you.

No problem, send me an email with your shipping address.

**Comment by Townie-au** [comment]
Thankyou 👍👍👍
What's your email?

**Comment by markniu** [comment]
niujl123@sina.com

**Comment by Townie-au** [comment]
I've sent you the email mark and I've ordered the adapter. Should get here Tuesday. 
What commands do I send to retrieve the data?

**Comment by markniu** [comment]
> I've sent you the email mark and I've ordered the adapter. Should get here Tuesday. What commands do I send to retrieve the data?

any serial software is ok, like pronterface.  no command needed.

**Comment by Townie-au** [comment]
> > I've sent you the email mark and I've ordered the adapter. Should get here Tuesday. What commands do I send to retrieve the data?
> 
> any serial software is ok, like pronterface. no command needed.

Does it need to be plugged into the printer as well or just read it straight from the sensor?

What do I need to look for?

**Comment by markniu** [comment]
no need to be plugged into the printer.  there will be some message output after it is powered on, and many raw data output. then we can confirm whether this sensor works well.

**Comment by Townie-au** [comment]
Ok. Have it hooked to the serial to usb adapter, opened with putty. Some data coming out. Changes when metal near. Dont know what to make of it.

**Comment by Townie-au** [comment]
64▒$4▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒yy▒4e▒▒▒G▒5▒▒▒55▒䊊▒F▒▒!!1▒▒F▒!▒▒▒▒)▒▒))▒▒▒▒▒N▒▒▒▒▒D▒5ڃ▒%!▒▒▒!▒͂▒▒!▒▒1▒▒1▒▒▒▒5▒1▒!!!▒▒▒▒▒▒▒▒▒▒▒)▒▒▒▒▒▒9▒▒9▒▒▒9▒5▒▒Ń▒▒)▒i▒▒)))9▒▒▒▒▒▒▒▒▒▒)▒▒599▒▒▒▒▒9▒)▒▒▒)▒▒%ձ45)▒▒▒▒▒▒5)▒)▒)5▒▒)▒▒▒▒5▒▒▒5)▒%▒ɱ▒▒ʂ▒▒▒)▒▒▒▒▒▒ł)▒▒▒▒▒▒▒▒▒▒)▒)D▒▒▒)))▒▒▒d▒▒▒d▒▒▒▒▒g▒)▒5▒▒)▒▒▒▒䙂▒d▒▒4▒▒▒))▒)▒)5))i▒▒)▒▒)▒▒▒▒▒▒▒▒₂▒▒▒▒䂂)▒)▒▒▒▒)▒▒▒▒▒▒▒▒ʶ▒▒▒)▒▒)▒▒▒▒▒▒▒▒▒▒▒▒)5▒▒))▒▒5▒▒ʂ▒▒)D▒▒▒▒▒▒)i▒▒▒▒▒▒▒▒5▒▒▒▒▒▒▒▒̂▒䂾5▒▒▒▒▒▒▒▒▒▒▒▒▒▒)▒

**Comment by markniu** [comment]
> 64▒$4▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒yy▒4e▒▒▒G▒5▒▒▒55▒䊊▒F▒▒!!1▒▒F▒!▒▒▒▒)▒▒))▒▒▒▒▒N▒▒▒▒▒D▒5ڃ▒%!▒▒▒!▒͂▒▒!▒▒1▒▒1▒▒▒▒5▒1▒!!!▒▒▒▒▒▒▒▒▒▒▒)▒▒▒▒▒▒9▒▒9▒▒▒9▒5▒▒Ń▒▒)▒i▒▒)))9▒▒▒▒▒▒▒▒▒▒)▒▒599▒▒▒▒▒9▒)▒▒▒)▒▒%ձ45)▒▒▒▒▒▒5)▒)▒)5▒▒)▒▒▒▒5▒▒▒5)▒%▒ɱ▒▒ʂ▒▒▒)▒▒▒▒▒▒ł)▒▒▒▒▒▒▒▒▒▒)▒)D▒▒▒)))▒▒▒d▒▒▒d▒▒▒▒▒g▒)▒5▒▒)▒▒▒▒䙂▒d▒▒4▒▒▒))▒)▒)5))i▒▒)▒▒)▒▒▒▒▒▒▒▒₂▒▒▒▒䂂)▒)▒▒▒▒)▒▒▒▒▒▒▒▒ʶ▒▒▒)▒▒)▒▒▒▒▒▒▒▒▒▒▒▒)5▒▒))▒▒5▒▒ʂ▒▒)D▒▒▒▒▒▒)i▒▒▒▒▒▒▒▒5▒▒▒▒▒▒▒▒̂▒䂾5▒▒▒▒▒▒▒▒▒▒▒▒▒▒)▒

what's the baud rate? the baud rate should be 115200

**Comment by Townie-au** [comment]
> > 64▒$4▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒yy▒4e▒▒▒G▒5▒▒▒55▒䊊▒F▒▒!!1▒▒F▒!▒▒▒▒)▒▒))▒▒▒▒▒N▒▒▒▒▒D▒5ڃ▒%!▒▒▒!▒͂▒▒!▒▒1▒▒1▒▒▒▒5▒1▒!!!▒▒▒▒▒▒▒▒▒▒▒)▒▒▒▒▒▒9▒▒9▒▒▒9▒5▒▒Ń▒▒)▒i▒▒)))9▒▒▒▒▒▒▒▒▒▒)▒▒599▒▒▒▒▒9▒)▒▒▒)▒▒%ձ45)▒▒▒▒▒▒5)▒)▒)5▒▒)▒▒▒▒5▒▒▒5)▒%▒ɱ▒▒ʂ▒▒▒)▒▒▒▒▒▒ł)▒▒▒▒▒▒▒▒▒▒)▒)D▒▒▒)))▒▒▒d▒▒▒d▒▒▒▒▒g▒)▒5▒▒)▒▒▒▒䙂▒d▒▒4▒▒▒))▒)▒)5))i▒▒)▒▒)▒▒▒▒▒▒▒▒₂▒▒▒▒䂂)▒)▒▒▒▒)▒▒▒▒▒▒▒▒ʶ▒▒▒)▒▒)▒▒▒▒▒▒▒▒▒▒▒▒)5▒▒))▒▒5▒▒ʂ▒▒)D▒▒▒▒▒▒)i▒▒▒▒▒▒▒▒5▒▒▒▒▒▒▒▒̂▒䂾5▒▒▒▒▒▒▒▒▒▒▒▒▒▒)▒
> 
> what's the baud rate? the baud rate should be 115200

▒▒;#!)#qaa▒▒▒s▒▒▒▒▒cy▒▒{▒▒k▒▒k▒▒O1015,F79,S-1
                                             O823,F305,S-1
                                                          O3,F10,S-1
                                                                    O1015,F268,S-1
  O497,F560,S-1
               O536,F579,S-1
                            O558,F674,S-1
                                         O651,F688,S-1
                                                      O645,F679,S-1
                                                                   O651,F684,S-1
                                                                               O650,F687,S-1
            O660,F706,S-1
                         O681,F730,S-1
                                      O705,F749,S-1
                                                   O708,F736,S-1
                                                                O689,F718,S-1
                                                                             O683,F725,S-1
          O696,F733,S-1
                       O699,F730,S-1
                                    O693,F729,S-1
                                                 O695,F733,S-1
                                                              O700,F739,S-1
                                                                           O708,F750,S-1
        O719,F758,S-1
                     O727,F767,S-1
                                  O733,F771,S-1
                                               O739,F781,S-1
                                                            O751,F792,S-1
                                                                         O755,F794,S-1
      O760,F801,S-1
                   O764,F799,S-1
                                O763,F803,S-1
                                             O773,F815,S-1
                                                          O780,F815,S-1
                                                                       O771,F804,S-1
    O764,F801,S-1
                 O770,F815,S-1
                              O776,F806,S-1
                                           O761,F801,S-1
                                                        O766,F801,S-1
                                                                     O764,F800,S-1
  O763,F799,S-1
               O765,F802,S-1
                            O767,F805,S-1
                                         O769,F805,S-1
                                                      O764,F795,S-1
                                                                   O760,F797,S-1
                                                                               O758,F795,S-1
            O761,F799,S-1
                         O765,F804,S-1
                                      O756,F777,S-1
                                                   O1015,F697,S-1
                                                                 O137,F209,S-1
                                                                              O201,F270,S-1
           O251,F277,S-1
                        O253,F281,S-1
                                     O264,F308,S-1
                                                  O262,F295,S-1
                                                               O272,F748,S-1
                                                                            O729,F822,S-1
         O558,F615,S-1
                      O533,F549,S-1
                                   O500,F528,S-1
                                                O499,F534,S-1
                                                             O509,F550,S-1
                                                                          O519,F547,S-1
       O514,F539,S-1
                    O493,F521,S-1
                                 O490,F522,S-1
                                              O498,F541,S-1
                                                           O517,F550,S-1
                                                                        O517,F544,S-1
     O511,F538,S-1
                  O507,F537,S-1

**Comment by markniu** [comment]
that's the raw data from the mcu, and seems the sensor works well.

**Comment by Townie-au** [comment]
> that's the raw data from the mcu, and seems the sensor works well.

So why the error in mainsail mark?

**Comment by Townie-au** [comment]
> that's the raw data from the mcu, and seems the sensor works well.

I want it to work again. :(
Where do we go from here?

**Comment by markniu** [comment]
I think it only to check the connection/pin number and try to increase the delay value in the BDsensor section.

**Comment by Townie-au** [comment]
Hey Mark
Thank you so much for sending the new sensor. 
It worked straight away. With the cable I was using before. I didn't use your one because it's too long just to go to the tool head and I didn't want to cut it. 
Unless it's an intermittent thing. I'll keep you posted.
How do I use the realtime leveling?
