### ISSUE TITLE
Spider v2.3

### ISSUE THREAD

**Issue by Eloura74** [markniu/Bed_Distance_sensor#118]
hello everyone, well I have quite a few problems after the compilation:
 1st-I have to reflash 1 each time my motherboard during a save config..... 
2nd-I would like to know exactly the pins where to connect  the bdsendor on the spider v2.3.  thank you all

**Comment by markniu** [comment]
I think this is the boot mode problem, maybe something wrong about the flash address in your flash command.
as we have discussed in the facebook, you can check again the flash document of spider.
