### ISSUE TITLE
Uninstall doesn't revert changes to `scripts/buildcommands.py`

### ISSUE THREAD

**Issue by dhoard** [markniu/Bed_Distance_sensor#122]
When performing an uninstall, the change to `scripts/buildcommands.py`made during installation...

```
sed 's/--dirty//g' "${HOME_DIR}/scripts/buildcommands.py" -i
```

... isn't reverted

**Comment by markniu** [comment]
you can run this in the folder klipper to reset.
`git reset --hard`

**Comment by dhoard** [comment]
@markniu I'm curious why you closed the issue without actually fixing it.

You provided a workaround, which is great, but the core issue still remains in the uninstall script.

**Comment by markniu** [comment]
thanks, I just updated the uninstall.sh file for the buildcommands.py file recovery
