### ISSUE TITLE
Bed_mesh issue after last update

### ISSUE THREAD

**Issue by luco85** [markniu/Bed_Distance_sensor#123]
Hi mark i just update bdsensor and  after i received this error
![image](https://github.com/markniu/Bed_Distance_sensor/assets/68059403/7b9fcd71-43d6-4818-a7d8-b5b9adee317b)
I have bed_mesh section in my config file as before

**Comment by luco85** [comment]
Now work, i had a uppercase  word. Before this error was bed_mesh is not a valid object. Need to delete bede_mesh default section under bottom klipper section save. I save my bed mesh. Maybe the name bed_mesh cause error

**Comment by qp1306** [comment]
I have the same error how do we fix it?

**Comment by qp1306** [comment]
<img width="604" alt="Screenshot 2024-04-23 at 16 06 54" src="https://github.com/markniu/Bed_Distance_sensor/assets/25638458/13bb04d2-df45-4f2b-bedd-598b9514bef8">

**Comment by markniu** [comment]
sorry, I just reverted back the last change that will may cause error in some case, if the section [bed_mesh] is below the [BDsensor]

**Comment by luco85** [comment]
Search another section that have bed_mesh words an try to delete
Look at botton if your config file where klipper save his section

**Comment by qp1306** [comment]
Thanks all working again after that quick update

**Comment by luco85** [comment]
@markniu thanks! Considering that somebody (like me) have the bdsensor section in an external file cfg
