### ISSUE TITLE
Klipper calibration issue

### ISSUE THREAD

**Issue by dhoard** [markniu/Bed_Distance_sensor#126]
I had to rebuild my Klipper machine, so I needed to recalibrate the printer/BDsensor.

I ran through the [instructions](https://github.com/markniu/Bed_Distance_sensor/wiki/Installing-for-Klipper ) and found that I had issues at [step 5](https://github.com/markniu/Bed_Distance_sensor/wiki/Installing-for-Klipper#5-calibration).

"Send command SET_KINEMATIC_POSITION Z=50  then move the Z axis down in the menu until the nozzle just touches the bed plate, the BDsensor will use this position as the zero position."

If the toolhead is located further than 50mm above the print plate when issuing the command, then Klipper wouldn't allow enough Z movement to move the nozzle down to "just touch the bed."

```
Move out of range: 0.000 0.000 -.100 [0.000]
```

I worked around the issue by...

1. disabling the steppers in Klipper
2. manually rotating the Z lead screw(s) so that the nozzle "just touches the bed."
3. issuing `SET_KINEMATIC_POSITION Z=0`
4. continue with the remaining calibration instructions

Post-calibration tests seem correct.

Thoughts on changing the instructions?

**Comment by markniu** [comment]
seems the 50mm is not enough, you can set it to 200, `SET_KINEMATIC_POSITION Z=200`  I also have updated that in the instruction.
