### ISSUE TITLE
Always read 0.0mm

### ISSUE THREAD

**Issue by semos2k** [markniu/Bed_Distance_sensor#132]
Hi, i installed bd sensor 1.2 firmware using ebb36 over canbus on my printer bud on send gcode M102 S-2 always read 0.0mm the led in sensor turn on when metal is near.

Thanks

**Comment by markniu** [comment]
first check the communication by sending M102 S-1?  if there is no problem then need to calibrate the BDsensor else it will return 0

**Comment by semos2k** [comment]
The comunication work correctly, m102 s-1 works

**Comment by markniu** [comment]
then need calibrate the sensor.

**Comment by semos2k** [comment]
If you are right, it has worked perfectly, I was afraid because the documentation and several videos showed that without calibrating it should show the distance.

Thanks for your help, amazing product.
