### ISSUE TITLE
'BDsensor_Version' command shutsdown Klipper

### ISSUE THREAD

**Issue by KiwiChrist** [markniu/Bed_Distance_sensor#149]
Entering M102 S-1 into the Klipper displays the BDsensor firmware version fine however, entering BDSENSOR_VERSION into the console shuts down klipper. 

Not too sure why it's doing this??

<img width="473" alt="image" src="https://github.com/markniu/Bed_Distance_sensor/assets/20054687/3bc7e925-35b5-49e4-bbe1-cfb22d319668">

**Comment by markniu** [comment]
thanks, there is a bug in BDSENSOR_VERSION and now it is fixed, you can just update the BDsensor.py and restart the klipper.

**Comment by KiwiChrist** [comment]
I can report back that indeed it now works with the update.
