### ISSUE TITLE
Can't compile firmware in klipper

### ISSUE THREAD

**Issue by neshami** [markniu/Bed_Distance_sensor#15]
here is output
 Building out/compile_time_request.o
Version: 66ede55
  Preprocessing out/src/generic/armcm_link.ld
  Linking out/klipper.elf
make: scripts/check-gcc.sh: Permission denied
make: *** [Makefile:73: out/klipper.elf] Error 127

**Comment by markniu** [comment]
it seems the permission denied, just run `chmod 777 ./scripts/*` in the klipper folder
