### ISSUE TITLE
Real Time update fail: update z must be >0

### ISSUE THREAD

**Issue by Townie-au** [markniu/Bed_Distance_sensor#150]
BDsensorVer:V1.2c pandapi3d ,switch_mode=1,collision_homing=1,collision_cal=1

About a minute into the print, halts printer.

**Comment by Townie-au** [comment]
[logs-20240611-154328.zip](https://github.com/user-attachments/files/15782830/logs-20240611-154328.zip)

**Comment by markniu** [comment]
here the actual error is the timer too close, and I will change this message `fail: update z must be >0 ` as a warning message later.
you can add `rt_sample_time:20 ` into the BDsensor section,here 20 means the distance reading sample time is 20ms.
The value of rt_sample_time depends on the MCU speed, please increase this value if the MCU speed is low.

**Comment by Townie-au** [comment]
Different error this time
[Uploading klippy.log (13).txt…]()

**Comment by markniu** [comment]
Seems the klippy.log file was not updated successfully.
> Different error this time Uploading klippy.log (13).txt…

**Comment by Townie-au** [comment]
CPU: Allwinner H616, Quad-core Cortex-A53 @1.5GHz

**Comment by markniu** [comment]
> Different error this time Uploading klippy.log (13).txt…

could you update the klippy.log file again?  and I cann't download this file

**Comment by Townie-au** [comment]
[klippy.log (13).txt](https://github.com/user-attachments/files/15884429/klippy.log.13.txt)

**Comment by markniu** [comment]
did the error " Unable to read tmc uart 'stepper_z' register GSTAT" happen in the first layer?

**Comment by Townie-au** [comment]
Yes

**Comment by Townie-au** [comment]
BD sensor and klipper were out of date. 
I updated it this morning. I'll give it another go when I get home.

**Comment by markniu** [comment]
> did the error " Unable to read tmc uart 'stepper_z' register GSTAT" happen in the first layer?

and I think this should be the same as the error `timer too close`, you can adjust the the `rt_sample_time: ` to 25 or 30

**Comment by Townie-au** [comment]
What does this mean?

Real Time update fail: update z must be >0

3:45 PM

Real time leveling height:0.20 ( 0.20 z_offset:0.00)

Andrew

**Comment by Townie-au** [comment]
[klippy.log (14).txt](https://github.com/user-attachments/files/15896216/klippy.log.14.txt)

**Comment by Townie-au** [comment]
On the bottom of printer.cfg it has this


747 #*# [BDsensor]

748 #*# z_adjust = 0.0

749 #*# z_offset = 0

**Comment by Townie-au** [comment]
So changing rt_sample_time: to 30. Seems to have worked but still getting the real time update fail error in the console but print continuing.

**Comment by markniu** [comment]
> What does this mean? Real Time update fail: update z must be >0 3:45 PM Real time leveling height:0.20 ( 0.20 z_offset:0.00) 

that means it will not adjust the z height while printing because the current z position is <0 or higher than setting value

**Comment by markniu** [comment]
> > What does this mean? Real Time update fail: update z must be >0 3:45 PM Real time leveling height:0.20 ( 0.20 z_offset:0.00)
> 
> that means it will not adjust the z height while printing because the current z position is <0 or higher than setting value

I have changed this message, and this message is normal sometimes because the z maybe changed in the first layer,for example the intro line in the start gcode in the slicer or retraction

**Comment by Townie-au** [comment]
Nope. Shutdown 6% in timer too close EBBCan
[klippy.log (15).txt](https://github.com/user-attachments/files/15899128/klippy.log.15.txt)

**Comment by markniu** [comment]
> Nope. Shutdown 6% in timer too close EBBCan [klippy.log (15).txt](https://github.com/user-attachments/files/15899128/klippy.log.15.txt)

did it happen in the first layer? if not make sure there is a `BDSENSOR_SET REAL_TIME_HEIGHT=0` after first layer in the gcode file to disable this feature.

in theory, if it is disabled after first layer by `BDSENSOR_SET REAL_TIME_HEIGHT=0`  , then there is no any code of BDsensor running both in linux or mcu.

**Comment by Townie-au** [comment]
Yeah that's what I thought. I have that gcode in already.
I'll try it with a bed mesh and see how it goes.

**Comment by feral42** [comment]
any updates on this?  I'm having the same problem.

**Comment by Townie-au** [comment]
I managed to get real time levelling working.

I didnt remove all bed mesh related sections in my printer.cfg and I changed rt_sample_time to 16ms.
