### ISSUE TITLE
QGL Shuts Down Klipper

### ISSUE THREAD

**Issue by KiwiChrist** [markniu/Bed_Distance_sensor#152]
Doing a QGL on my Voron now shuts down klipper firmware on the first pass at the 4th point of the QGL sequence.
The error displayed twice is   **Internal error on command:"_QUAD_GANTRY_LEVEL"** 

Please note: this same error now occurs on my other printer that uses the "z_tilt" command and the BDsensor "Z_TILT_ADJUST" macro.  Klipper is shut down on the first pass at the second point of the z_tilt sequence.

Things I have done:
Updated BDsensor QGL "QUAD_GANTRY_LEVEL" macro. No fix.
Updated BDsensor Klipper firmware on the MCU's. No fix.
Set BDsensor cfg's to default settings. No fix.

I suspect that it actually Klipper being the issue as removing the BDsensor macros I still get an error.

Any ideas for a solution?

Voron Clips
<img width="549" alt="image" src="https://github.com/markniu/Bed_Distance_sensor/assets/20054687/d13fee03-21cd-4f3e-adbb-232768e05d40">

<img width="437" alt="image" src="https://github.com/markniu/Bed_Distance_sensor/assets/20054687/56e90893-71e3-47cb-b1f3-416492e90015">

<img width="610" alt="image" src="https://github.com/markniu/Bed_Distance_sensor/assets/20054687/4b8f77e1-8f5b-4eaa-a8ff-abf0757b12f9">

Other Printer Clip
<img width="506" alt="image" src="https://github.com/markniu/Bed_Distance_sensor/assets/20054687/652eb2ad-3740-4048-a719-8580679e91f3">

**Comment by markniu** [comment]
Hello, thanks for feedback this, 
and I just checked that the reason is the official klipper had updated the probe.py today, and the code of BDsensor.py needs to updated too, now I am testing, I will update it to my github late.

**Comment by KiwiChrist** [comment]
Yeah... I removed the BDsensor macros and am still getting the error so I came to the same conclusion. Thanks.

**Comment by KiwiChrist** [comment]
Thanks for the quick response and remedy.
