### ISSUE TITLE
dummy_gcode_cmd

### ISSUE THREAD

**Issue by Eloura74** [markniu/Bed_Distance_sensor#154]
![image](https://github.com/markniu/Bed_Distance_sensor/assets/95535946/c77ae910-4373-40fb-8d50-433b6532c7fa)
hello everyone, I replaced the probe with v1.3, reflash etc but I have had this error since then, someone could help me, thank you

**Comment by markniu** [comment]
thanks for feedback this, it is now fixed by sync the BDsensor.py code from official klipper probe.
