### ISSUE TITLE
Issue after last update with no_stop_probe

### ISSUE THREAD

**Issue by luco85** [markniu/Bed_Distance_sensor#157]
hi, after last update during mesh calibrate I had two errors (it work fine until update):
Internal error on command:"BED_MESH_CALIBRATE" 
I notice that after update the probe movements stop on every point. I have no_stop_probe: in my bd section but nothing change
I update all and refreshing all mcu, now mesh calibrate works (seems) but the probe stops on every point

**Comment by markniu** [comment]
thanks for feedback this new bug, and please update the BDsensor.py and try again.

**Comment by luco85** [comment]
well, now it work again! thanks @markniu
