### ISSUE TITLE
STC version lacks contact probe firmware

### ISSUE THREAD

**Issue by oliof** [markniu/Bed_Distance_sensor#161]
Hi,
the STC version of the probe only is updated up to firmware version 1.1

Are there any plans to provide firmware with contact probe support for STC based Bed Distance sensors?

**Comment by markniu** [comment]
yes, the firmware of contact probe for the STC  and STM32  are updated at the same time:
 V1_1BDsensor20240213.hex: https://github.com/markniu/Bed_Distance_sensor/tree/new/hex/V1.1_STC

**Comment by oliof** [comment]
Thank you for the clarification.
