### ISSUE TITLE
Internal error during mesh calibrate

### ISSUE THREAD

**Issue by heinrichWeichert** [markniu/Bed_Distance_sensor#163]
Latest HEAD patched into Klipper.

MCU is stopped after going to the last mesh point

klippy.log attached
[klippy_snip.log](https://github.com/user-attachments/files/16202607/klippy_snip.log)

**Comment by markniu** [comment]
do you use the latest klipper? I just tested OK with the latest klipper. the latest code of bdsensor does not work with the old klipper because the official klipper changed a lot about the probe last month.

**Comment by Townie-au** [comment]
I had this issue.
horizontal_move_z: in bed_mesh was too high. Changed it to 1.

Andrew

**Comment by heinrichWeichert** [comment]
Yes, klipper is up-to-date. I'll check the horizontal_move, thanks.

**Comment by heinrichWeichert** [comment]
I changed the values to 
sample_retract_dist: 0.2
And
horizontal_move_z: 0.2

works but there is no second pass 
I guess that has to do with Klipper changes
