### ISSUE TITLE
Sensor triggers in air

### ISSUE THREAD

**Issue by RealHaltewunsch** [markniu/Bed_Distance_sensor#172]
I have the BDsensor M, I calibrated it and imI'm using these parameters: BDsensorVer:V1.2c,switch_mode=1,collision_homing=1,collision_cal=1

My config includes
[force_move] 
enable_force_move: true

Still, every other time I try to print my probe triggers in air. The nozzle has a distance of about 3-5mm, the probe still has about 4-6mm distance to the bed.
Sometimes it triggers the first time correctly, but then on the second try it triggers in air and keeps going up and up and up.
I noticed that when the bed is heating I have a 0% chance of homing, so now I turn the heaters off before probing the bed, but still every other time it triggers in air and never finishes homing.

Klipper gives me following error:
warning: triggered in air, 743
BDsensorVer:V1.2c,switch_mode=1,collision_homing=1,collision_cal=1

My calibration reading is:
`17:10
805 at 3.9mm
17:10
797 at 3.8mm
17:10
783 at 3.7mm
17:10
783 at 3.6mm
17:10
776 at 3.5mm
17:10
767 at 3.4mm
17:10
758 at 3.3mm
17:10
751 at 3.2mm
17:10
742 at 3.1mm
17:10
731 at 3.0mm
17:10
720 at 2.9mm
17:10
710 at 2.8mm
17:10
697 at 2.7mm
17:10
685 at 2.6mm
17:10
673 at 2.5mm
17:10
658 at 2.4mm
17:10
643 at 2.3mm
17:10
631 at 2.2mm
17:10
616 at 2.1mm
17:10
601 at 2.0mm
17:10
581 at 1.9mm
17:10
544 at 1.8mm
17:10
545 at 1.7mm
17:10
526 at 1.6mm
17:10
503 at 1.5mm
17:10
487 at 1.4mm
17:10
462 at 1.3mm
17:10
439 at 1.2mm
17:10
416 at 1.1mm
17:10
395 at 1.0mm
17:10
372 at 0.9mm
17:10
343 at 0.8mm
17:10
319 at 0.7mm
17:10
294 at 0.6mm
17:10
267 at 0.5mm
17:10
246 at 0.4mm
17:10
222 at 0.3mm
17:10
199 at 0.2mm
17:10
174 at 0.1mm
17:10
153 at 0.0mm`

What can I do about it?

[config-20240813-171339.zip](https://github.com/user-attachments/files/16601625/config-20240813-171339.zip)
[klippy.log](https://github.com/user-attachments/files/16601626/klippy.log)

**Comment by markniu** [comment]
seems need to increase the second homing speed.  set the `second_homing_speed `from 3 to 4 or 5

**Comment by HelmutPirker** [comment]
Bei mir ist das jetzt auch der Fehler **warning: triggered in air ** angezeigt,. eine Erhörung  der zweiten Homing- Geschwindigkeit behebt den Fehler nicht. Was jetzt?

**Comment by RealHaltewunsch** [comment]
@markniu thanks for your help, this solved it for me, I have set it to 4 and it homes fine every time.

**Comment by Clarkbf** [comment]
I am having the same issue. When it fails though my bed slowly moves down (coreXY) until it crashes the bed into the bottom of the printer. The printer never stops the homing cycle unless I emergency stop the print. 
my Z klipper stepper settings:

homing_speed: 6.0 # Leadscrews are slower than 2.4, 10 is a recommended max.
second_homing_speed: 5
homing_retract_dist: 6
homing_retract_speed: 10

**Comment by markniu** [comment]
you can test with the slow speed at first ,
like `homing_speed: 4.0` and `second_homing_speed: 3`  also setting the `delay:10` value in `BDsensor `section

> I am having the same issue. When it fails though my bed slowly moves down (coreXY) until it crashes the bed into the bottom of the printer. The printer never stops the homing cycle unless I emergency stop the print. my Z klipper stepper settings:
> 
> homing_speed: 6.0 # Leadscrews are slower than 2.4, 10 is a recommended max. second_homing_speed: 5 homing_retract_dist: 6 homing_retract_speed: 10

**Comment by Clarkbf** [comment]
I have the delay value already at 10. Can this be a larger number? Wondering if retract distance should be adjusted as well? set to 6 right now.

**Comment by markniu** [comment]
The delay value affects the communication speed of MCU with BDsensor. The larger the value, the slower the communication speed.   
that retract_distance:6 is ok.

**Comment by Clarkbf** [comment]
Why does the bed continue to move away from the bdsensor when it has the triggered in air issue and is there a way to stop it?
