### ISSUE TITLE
No data or corrupt data from BDsensor(), Please check connection

### ISSUE THREAD

**Issue by MDegelmann** [markniu/Bed_Distance_sensor#185]
Hello, I can't get a connection
I use the Manta M8P and since the pins

sda_pin: PC9
scl_pin: PA8

Firmware is flashed and the version is: v0.12.0-316-g96cceed23-dirty

the sensor is v1.3

don't know what to do next

**Comment by markniu** [comment]
how about use the probe pins:
sda_pin: PD13
scl_pin: PD12

**Comment by MDegelmann** [comment]
The same problem No data or corrupt data from BDsensor( ), Please check connection

**Comment by markniu** [comment]
does the light on while put a metal close the coil?  check again the 5v and other wire order.

**Comment by MDegelmann** [comment]
111 / 5.000
Yes, the LED lights up when you hold a piece of metal to it.

I have checked all connections
GND
5V
SCL
GND
SDA

**Comment by markniu** [comment]
What does the cable that comes with the BDsensor look like?

**Comment by MDegelmann** [comment]
I measured the cable and everything has contact

**Comment by markniu** [comment]
it can not be measured by multimeter sometimes.  what's the delay value in the BDsensor section? you can try to increase that value.

**Comment by MDegelmann** [comment]
I was able to solve the problem.

I flashed the sensor and now it works

**Comment by ceb0610** [comment]
Having the same problem but not having any luck flashing my sensor.

**Comment by markniu** [comment]
> Having the same problem but not having any luck flashing my sensor.

which board and pins are used for the sensor?

**Comment by ceb0610** [comment]
> > Having the same problem but not having any luck flashing my sensor.
> 
> which board and pins are used for the sensor?

BD Sensor V1.3
ST-Link V2 connected according to the wiki. I have checked the wiring multiple times.

When I connect everything the sensor lights up when I get it close to metal, so I think the sensor is working.


![IMG_20241018_211902075](https://github.com/user-attachments/assets/b76e4049-beab-4dcc-9b24-f8514c4b75ab)

**Comment by markniu** [comment]
sorry, I mean which the pins are used for the sensor on the mainboard of the printer?


> > 
> > which board and pins are used for the sensor?
> 
> BD Sensor V1.3 ST-Link V2 connected according to the wiki. I have checked the wiring multiple times.
> 
> When I connect everything the sensor lights up when I get it close to metal, so I think the sensor is working.

**Comment by ceb0610** [comment]
> sorry, I mean which the pins are used for the sensor on the mainboard of the printer?
> 
> > > which board and pins are used for the sensor?
> > 
> > 
> > BD Sensor V1.3 ST-Link V2 connected according to the wiki. I have checked the wiring multiple times.
> > When I connect everything the sensor lights up when I get it close to metal, so I think the sensor is working.

Using the BLTouch interface on my toolhead board. Getting 5V from another connector.

[BDsensor] 
sda_pin:extra_mcu:PB6 
scl_pin:extra_mcu:PB7

![Untitled](https://github.com/user-attachments/assets/34da71a5-eaba-4405-a8d1-8d19af88e5ed)

**Comment by markniu** [comment]
do you have the electronic schematic ? you can check if there is a capacitor on the PB6 on the board

**Comment by ceb0610** [comment]
> do you have the electronic schematic ? you can check if there is a capacitor on the PB6 on the board

No capacitor.

**Comment by MDegelmann** [comment]
Problem durch neues flashen der Hardware gelöst
