### ISSUE TITLE
Question: What is the operating temperature/ melting point?

### ISSUE THREAD

**Issue by billgeek** [markniu/Bed_Distance_sensor#20]
As most that have built a Voron extruder will know, inductive probes tend to melt due to the constant exposure of the probe to the heated bed, especially when printing using ABS where the bed sits at around 85C.

What temperature resistance does this sensor have and will it deform or melt while in operation?

**Comment by markniu** [comment]
the max operating temperature of all the components is above 80C including the wires.
the max work temperature of the inside coil is 120C, and 170C for the nylon case.
