### ISSUE TITLE
Internal error on command:"BED_MESH_CALIBRATE"

### ISSUE THREAD

**Issue by ACrook311** [markniu/Bed_Distance_sensor#200]
I've tried both the fixes "position_min: 0" in stepper z and "no_stop_probe:" with and without being commented out, that I've found when researching the BED_MESH_CALIBRATE error I am getting, to no avail.  I'll include what I think to be the only relevant parts of my cfg file.  Hopefully this format for sending this info is acceptable, and my apologies if not.  I'm thinking it has something to do with [delayed_gcode_bed_mesh] part, but no real reasoning for thinking that, other than its a copy and paste from some of my other printers running a BL Touch.  

And the printer goes through the whole process of scanning the bed, only to error once complete.  

# Motor3
[stepper_z]
step_pin: PB8
dir_pin: !PB7
enable_pin: !PE0
microsteps: 16
rotation_distance: 4 #8
endstop_pin: probe:z_virtual_endstop #^PF2
#position_endstop: 0
position_max: 400
position_min: 0 #-5.0
homing_speed: 5
second_homing_speed: 3
#homing_retract_speed: 2
homing_retract_dist: 5

[safe_z_home]
home_xy_position: 165,165

[bed_mesh]
speed: 100
mesh_min:40,40
mesh_max:300,300
probe_count: 6,6
horizontal_move_z:1 # 0.7~1.0mm is recommended
algorithm: bicubic  # this should be bicubic if the bed mesh points count is > 6*6

[delayed_gcode bed_mesh_init]
initial_duration: .01
gcode: BED_MESH_PROFILE LOAD=default

[force_move] 
enable_force_move: true   # required by the command SET_KINEMATIC_POSITION in the calibration step below.

[BDsensor] 
# Don't use aliases for the board pins
sda_pin: PD13 # example of connecting to main board Creality V4.2.7
scl_pin: PD12
#scl_pin:MKS_THR:gpio20 # example of connecting to CAN module like MKS THR42 
#sda_pin:MKS_THR:gpio11 
#scl_pin:host:gpio17 # example of connecting to GPIO on RaspberryPi
#sda_pin:host:gpio27
delay: 20 # you can set it 10 if the BDsensor version is >=1.2
#z_offset:0 #  within -0.6 to 0.6mm
Z_adjust: 0
x_offset: 0
y_offset: 25
no_stop_probe: # fast probe that the toolhead will not stop at the probe point,disable it by commenting out.
position_endstop: 1.2 #the triggered position, recommend value is 1~2.8
collision_homing:1 #  set it 1 to enable homing with nozzle collision sensing.
collision_calibrate:1 # set it 1 to enable auto calibrate BDsensor with nozzle collision sensing.
#QGL_Tilt_Probe:0 #set 1 to enable probe up and down when do quad_gantry_level
Speed: 0.8

**Comment by ACrook311** [comment]
Here is the 1st error I find in Klippy.log.  How do I correct this?

bed_mesh: Unknown profile [default]
Script running error
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/extras/delayed_gcode.py", line 34, in _gcode_timer_event
    self.gcode.run_script(self.timer_gcode.render())
  File "/home/biqu/klipper/klippy/gcode.py", line 229, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/biqu/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/biqu/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/biqu/klipper/klippy/extras/bed_mesh.py", line 1398, in cmd_BED_MESH_PROFILE
    options[key](name)
  File "/home/biqu/klipper/klippy/extras/bed_mesh.py", line 1354, in load_profile
    raise self.gcode.error(
gcode.CommandError: bed_mesh: Unknown profile [default]
webhooks: registering remote method 'shutdown_machine' for connection id: 281472964181152
webhooks: registering remote method 'reboot_machine' for connection id: 281472964181152
webhooks: registering remote method 'pause_job_queue' for connection id: 281472964181152
webhooks: registering remote method 'start_job_queue' for connection id: 281472964181152

[klippy (12).log](https://github.com/user-attachments/files/18014146/klippy.12.log)

**Comment by markniu** [comment]
It seems the klipper in your printer is old, you can just replace the whole folder /home/biqu/klipper/ with latest klipper

![image](https://github.com/user-attachments/assets/f726a8f4-ed21-4435-ba6d-d541faa8e432)

**Comment by ACrook311** [comment]
I’ll gladly give it another try, but it’s like my 3rd time reinstalling
klipper.

I 1st updated what I had, that didn’t work, so I reinstalled it and updated
it again. This 3rd time is a fresh install, but it was the 1st time I was
able to get all 3 items to show the same version. Up to then, I was getting
a different error that what I was using was an old version and all 3 (mcu,
klipper, and one other part, I forget which) weren’t the same version.
Finally found on one of the groups how to get it showing “dirty” and that
got me to here.

Thanks a lot, appreciate the input.  So dont update via mainsail, and update in Kiauh?

**Comment by markniu** [comment]
you can also update the klipper directly like this:
```
cd ~
move klipper klipper_bak
git clone https://github.com/Klipper3d/klipper
```

**Comment by ACrook311** [comment]
![image](https://github.com/user-attachments/assets/2eae5a7c-c3ca-4a4f-b926-18b759e27f61)

biqu@BTT-CB1:~$ cd ~
move klipper klipper_bak
git clone https://github.com/Klipper3d/klipper
Command 'move' not found, did you mean:
  command 'jove' from deb jove
  command 'more' from deb util-linux
  command 'lmove' from deb suck
  command 'mmove' from deb mtools
Try: sudo apt install <deb name>
fatal: destination path 'klipper' already exists and is not an empty directory.
biqu@BTT-CB1:~$

Seems a copy and paste doesn't work, or I'm not in the correct dir.  I'm sure I'm probably missing an obvious step somewhere, but I've gone around and around with this enough I've gotten a little confused with the process.  Update Klipper seems easy enough.

Is updating through the update manager in Mainsail not a preferred method?  I usually go through Kiauh, for no particular reason.

![Ender 5](https://github.com/user-attachments/assets/aeae0fed-59b6-47d4-9bae-52bbf63d4d8f)

**Comment by markniu** [comment]
oh, sorry, it is not move but mv
```
cd ~
mv klipper klipper_bak
git clone https://github.com/Klipper3d/klipper
```
> you can also update the klipper directly like this:
> 
> ```
> cd ~
> move klipper klipper_bak
> git clone https://github.com/Klipper3d/klipper
> ```

**Comment by ACrook311** [comment]
![image](https://github.com/user-attachments/assets/8331b656-447f-4d46-bfb1-39d4f4c6c3be)

Was able to get the update ran, per your suggestion.  

Now is a different error, which I'm assuming has to do with assigning the endstop in z, with probe:z_virtual_endstop.  That tells me something happened in the klipper update, as now my config that was working is now not.  When I remove probe, it changes through a plethora of other issues, mainly with the BDsensor config portion.  

![image](https://github.com/user-attachments/assets/256157cd-d79a-42db-a84a-61386a14e5b8)

Just playing around, I've gotten it to register everything, down to the final error bdsensor is not a valid config.  I'm guessing I've made somewhat of a mess of my config, but that is easily corrected.  Any more suggestions?  Keep in mind, I've already tried several clean installs of Klipper

[klippy (13).log](https://github.com/user-attachments/files/18042456/klippy.13.log)

**Comment by ACrook311** [comment]
We did it Mark!   Since you suggested my issue was with updating, I went back through your install guide and notice the optional bd sensor update.  That has me going now!  I couldn't have done it without you.  Thanks!

cd  ~/Bed_Distance_sensor/
git fetch --all &&  git reset --hard origin/new && git pull

**Comment by ACrook311** [comment]
Probe stopped working.  Nothing changed with my setup, firmware, etc.  Just turned on the machine and the BD Sensor is not on.  I unplugged the sensor and plugged in a BLtouch, just to test out the wires, and it powered fine.  

The BD Sensor light is not on, but when I turn the machine on/off, it flashes.  Any thoughts?
