### ISSUE TITLE
Hotend adapter

### ISSUE THREAD

**Issue by ManuelPeiro** [markniu/Bed_Distance_sensor#21]
Hi,

I know its not an issue but I don't know how to ask this... if it's not here, I'm sorry. correct me.

Is there the possibility of getting a 3d model of the sensor? It would be to draw an adapter for my hotend.

And are there models of adapters to download? (To get ideas)

Thank you

**Comment by markniu** [comment]
Hi, here is the sensor coil case model and size I just move the stl_size folder into the root path: https://github.com/markniu/Bed_Distance_sensor/tree/new/stl_size
