### ISSUE TITLE
Open hardware, or commercial

### ISSUE THREAD

**Issue by punjabik** [markniu/Bed_Distance_sensor#22]
Is this project open hardware or commercial?

I cannot find schematics like in PandaCan and firmware of the board (if there is any).
I don't want to invest money in closed solution, so I'd like have answer to this question before buy and investing time.

Thank You.

**Comment by markniu** [comment]
I would like to open source this, but I really want to find a way to support me to continue working in the 3D printing world, sorry.

**Comment by ptegler** [comment]
??? Beacon, BLTouch, etc are not open source...why would you believe this is/should be?
klicky sure, it's just a switch and Klipper code, but none of the electronic solutions are open source.  I bought one of these very early on. I'm still waiting for a version that works with native Klipper (RatOS etc) or RepRap which are the two I use.

**Comment by punjabik** [comment]
> ??? Beacon, BLTouch, etc are not open source...why would you believe this is/should be?

Because I find this project on hackaday.io which is **repository of Open Hardware Projects** as they stated on their website.

So this is not open hardware project and should not use hackaday for gaining publicity and profit. I am glad, that I did not buy product and carefully check content of github first.

[markniu](https://github.com/markniu) there is plenty of ways how to support development.
Currently there is not even a simple button to send a donation.
