### ISSUE TITLE
MCU'S  need update

### ISSUE THREAD

**Issue by noohnak** [markniu/Bed_Distance_sensor#26]
MCU Protocol error

This is frequently caused by running an older version of the
firmware on the MCU(s). Fix by recompiling and flashing the
firmware.

MCU(s) which should be updated:
mcu: Current version v0.11.0-226-g0245073c
SB2040: Current version v0.11.0-235-gb9247810
Up-to-date MCU(s): none

[klippy (3).log](https://github.com/markniu/Bed_Distance_sensor/files/12169098/klippy.3.log)

**Comment by markniu** [comment]
did you flash the new firmware into SB2040  after patch the code of BDsensor?

**Comment by noohnak** [comment]
no i only changes the spider 2.2 controll board. i will try updating the can toolhewlead mcu also.

**Comment by noohnak** [comment]
am i supposed to do the toolhead also? So o i do it the same way as my control board?

**Comment by markniu** [comment]
> am i supposed to do the toolhead also? So o i do it the same way as my control board?

`make menuconfig` and choose the setting for SB2040 and `make `the new firmware for the SB2040, then flash into SB2040

**Comment by noohnak** [comment]
ok i flashed the sb2040 and still get

MCU Protocol error

This is frequently caused by running an older version of the
firmware on the MCU(s). Fix by recompiling and flashing the
firmware.

Your Klipper version is: v0.11.0-248-gd725dfd3-dirty
MCU(s) which should be updated:
mcu: Current version v0.11.0-226-g0245073c
SB2040: Current version v0.11.0-248-gd725dfd3
Up-to-date MCU(s):
<none>

[klippy (7).log](https://github.com/markniu/Bed_Distance_sensor/files/12182427/klippy.7.log)

**Comment by markniu** [comment]
seems you connect the BD sensor on the spider board? if in that case, could you try to make meuconfig and make for the spider firmware and flash into spider board again?

**Comment by markniu** [comment]
it report this error in the log file:msgproto.error: mcu 'mcu': Unknown command: I2C_BD_send

so check if there is a file BD_sensor.c in the folder klipper/src/ before make firmware

**Comment by noohnak** [comment]
so the only way i can get it to work is if i build and flash my board through kiauh. but then whn i go to save config after setup and restart firmware it gives error mcu's need update again.

**Comment by markniu** [comment]
could you read the distance value or the version information from the BDsensor after setup? 
one thing I suspect is the klipper has been updated by kiauh, so you can try to install the patch code for BDsensor again after running kiauh.

**Comment by noohnak** [comment]
Yes after loading firmware with kiauh I could control printer normally. and read value and version info. but then try to save and reload. klipper errors again

**Comment by markniu** [comment]
> 

Hello, I have not repeated this problem, could you attach the new klippy.log file?
