### ISSUE TITLE
I2C address

### ISSUE THREAD

**Issue by mammoth-3D-DevTeam** [markniu/Bed_Distance_sensor#32]
Hello markniu
I would like to test the Grove - 2-Channel Inductive Sensor (LDC1612) with your script. But the I2C address is 100% not the same.
The I2C address on the Seeed Grove - 2-Channel Inductive Sensor (LDC1612) is 0x28.

And what I would find in your files is that your board is using 0x20. Can I just change 0x20 to 0x28 or do I need to do something else?

Thanks for your help!

**Comment by markniu** [comment]
The difference from standard I2C is that there is no I2C address in BDsensor.
https://github.com/markniu/Bed_Distance_sensor/wiki/Data-Protocol
