### ISSUE TITLE
KAMP Adaptive_Meshing - Probe Position

### ISSUE THREAD

**Issue by KiwiChrist** [markniu/Bed_Distance_sensor#39]
Previous to installing the mighty little BDsensor I use Adaptive_Meshing, where the probe will only probe/mesh the area where the part is positioned on the print bed. KAMP as I understand accommodated for the position of the probe relative to the nozzle.  
KAMP does not seem to do this anymore with BDsensor.

Obviously the easy fix is to not include KAMP/Adaptive_Meshing and just scan the whole bed but I would like adaptive meshing to work.

The probe is set relative to the nozzle X-38 Y-8. But I cannot see where the BED_MESH_CALIBRATE compensates for the probe XY offset anywhere.

Is this a BDsensor issue or something else?

**Comment by markniu** [comment]
how about delete the no_stop_probe in the BDsensor?

**Comment by KiwiChrist** [comment]
No change when disabling no_stop_probe.
I have attached a sample of the printer.cfg to check if I have missed anything.

I assume [BDsensor] x_offset and y_offset are for the sensor position relative to the nozzle, as there no information for this on installation page. I can always set back to x0, y0 and see what happens.  ?

[Printercfg sample.txt](https://github.com/markniu/Bed_Distance_sensor/files/13340208/Printercfg.sample.txt)

Following on...
Zeroing x_offset and y-offset did nothing. Adaptive probing definitely being done at the nozzle position and not accounting for the probe position relative to the nozzle. I think it's more of a KAMP issue now.

**Comment by KiwiChrist** [comment]
I completely reset stepper_x's and stepper_y's position_endstop:, position_min: and position_max: and then setting the probe position to home in the center of the bed. I then checked [BDsensor] x_offset and y_offset making sure the probe offsets are correct. These did not seem to do much realtive to the nozzel.

After checking combinations of settings, I found that KAMP Adaptive_meshing did it's own thing, resizing the bed mesh area and probe offsets etc, therefore I do not think KAMP works with [BDsensor].  

I presume the problem is similar to the Beacon probe not working with KAMP.
So I'm disabling KAMPs Adaptive_Meshing and just doing a full bed scan.

**Comment by markniu** [comment]
The BDsensor uses the bed mesh points which generated by klipper, so it can be work with KAMP.

**Comment by KiwiChrist** [comment]
Via Klipper discord and with a whole day of testing yesterday I have come to the comclusion that the probe offsets xy in the [BDsensor] module are not being registered correctly and KAMP will never work properly.

The probing always occurs to the left of the bed center.

Mark, can you please confirm that the probe offset is working and registereing for KAMP to correctly run.

The image below are the results of a whole day testing and adjusting settings yesterday. 
Comparing the Test 1 to Test 2 the probe column does not alter it's configuration with the x39.5 and x-39.5 settings. 
The result remains as (84.7,84.7) respectively down the column with no difference.

Clearly the tool adjusted values do change from Test1 to Test 2, but the Probe column remains the same. Something is not being calculated correctly somewhere.

<img width="389" alt="image" src="https://github.com/markniu/Bed_Distance_sensor/assets/20054687/c7f7335d-ec51-4ff7-8bfc-ab75f8bed98a">

I beleive there is someting not implemented correctly in the BDsensor module.

Look forward to your reply.

**Comment by markniu** [comment]
> rs to the left of the bed center
This is normal, the points of the (84.7,84.7) is depends on the printing module. you can check it by switching it to other probe sensor.

**Comment by markniu** [comment]
> Via Klipper discord and with a whole day of testing yesterday I have come to the comclusion that the probe offsets xy in the [BDsensor] module are not being registered correctly and KAMP will never work properly.
> 
> The probing always occurs to the left of the bed center.
> 
> Mark, can you please confirm that the probe offset is working and registereing for KAMP to correctly run.
> 
> The image below are the results of a whole day testing and adjusting settings yesterday. Comparing the Test 1 to Test 2 the probe column does not alter it's configuration with the x39.5 and x-39.5 settings. The result remains as (84.7,84.7) respectively down the column with no difference.
> 
> Clearly the tool adjusted values do change from Test1 to Test 2, but the Probe column remains the same. Something is not being calculated correctly somewhere.
> 
> <img alt="image" width="389" src="https://private-user-images.githubusercontent.com/20054687/292647135-c7f7335d-ec51-4ff7-8bfc-ab75f8bed98a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTAzOTMsIm5iZiI6MTcwMzQ5MDA5MywicGF0aCI6Ii8yMDA1NDY4Ny8yOTI2NDcxMzUtYzdmNzMzNWQtZWM1MS00ZmY3LThiZmMtYWI3NWY4YmVkOThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA3NDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YTlmZTJkNTlhMzNjMGRhMWE3MGM5NTljZmM4M2EzMWExMzY4M2UwMzczYjA3MGIxMjM3Y2ZmOTYxOTMwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NrSRIxgjLLH4XBkqGszbgGvO3GxiFJAsI4fybEWHyEg">
> I beleive there is someting not implemented correctly in the BDsensor module.
> 
> Look forward to your reply.

This is normal, the points(84.7,84.7) is dependent on the printing model, so if you only change the x offset it will still the same. you can check it by switching it to other probe sensor.

**Comment by markniu** [comment]
The bed mesh points are the same as the original klipper, the BDsensor  has not changed any of that.

**Comment by KiwiChrist** [comment]
Hi Mark,
Yes I agree that KAMP is generating the mesh points but I think that BDsensor is fetching the incorrect column of points being generated by KAMP.

I am not sure how you it is being done as I am not a software Dev, but to me it looks like (referring to the image below) that BDsensor:gcode _BED_MESH_CALIBRATE "probe at X,Y" are points matching the "Probe" column of the KAMP generated points when is should be using the KAMP "Tool Adjusted" XY generated points.  Refer to image below...

With a BDsensor setup on another printer I have the exact same issue although in the Y direction. The difference is that the BDsensor relative to the nozzle positioned is X0, Y21 (the sensor is north of the nozzle).

My CFG settings for my Ender3v2.
[BDsensor] 
sda_pin: PC13 
scl_pin: PE5 
delay: 20 
z_offset: 0 
z_adjust: 0 
x_offset: -39.50 #probe position relative to nozzle
y_offset: 0  #probe position relative to nozzle
position_endstop: 0.8 

[bed_mesh]
speed: 60
horizontal_move_z: 1    #0.7~1.0mm is recommended
mesh_min: 19,24           #mesh_min and mesh_max are both relative to the probe. 
mesh_max: 222,226.5    #mesh_min and mesh_max are both relative to the probe. 
probe_count: 20,20        
algorithm: bicubic         #this should be bicubic if the bed mesh points count is > 6*6
fade_start: 1
fade_end: 10

<img width="855" alt="Points" src="https://github.com/markniu/Bed_Distance_sensor/assets/20054687/ae458ab8-cbe2-4e49-af68-8cb55ff51b18">

I think others have the same problem.... https://github.com/markniu/Bed_Distance_sensor/issues/66

Hopefully you can make sense of of this.
Jason.

**Comment by markniu** [comment]
Thanks! I check again and find that there is an option in the code that should be enabled for using XY offset.
please update the BDsensor.py

**Comment by KiwiChrist** [comment]
PERFECT! 
I can confirm that the BDsensor probe offset XY is now being implemented correctly and Adaptive Mesh is now working as expected.

This is now IMO the perfect little non contact probing device.
Great work!
