### ISSUE TITLE
Repo is dirty

### ISSUE THREAD

**Issue by LAZER555** [markniu/Bed_Distance_sensor#42]
Hi, i just installed bd sensor on klipper. And there's an error in an uplate section. What if i update klipper, will the bd sensor stop working?
![image](https://github.com/markniu/Bed_Distance_sensor/assets/131973076/f51795e7-78b4-4492-a206-2c78a34ee74c)

**Comment by Trash-Face** [comment]
~~What did you do to fix this? I'm having this issue now and i think its causing a random disconnect of the mcu.~~

FIgured it out.

**Comment by Trash-Face** [comment]
If anyone else is having this issue, you need to remake the klipper.bin after you have installed the BDsensor files. Re-Flash the mcu and reboot everything. 

If you want to use the newest version of klipper, you will need to update the host klipper install and then reinstall the BDsensor files before you remake the .bi
