### ISSUE TITLE
BD Sensor on MKS Nano6 3.3 Board

### ISSUE THREAD

**Issue by yardi83** [markniu/Bed_Distance_sensor#45]
Hi,

i`ve read that BD Sensor isn`t running on some Pins on MKS Boards. I wanna install it on my MKS Nano 6 3.3 OEM Board.
So just to clearify...BL-Touch Pins should work but Z- Endstop Pins won`t?
Which Pins would you suggest trying instead of Z- Endstop pin?

[MKS Nano6 V3.3_002 PIN Reborn2.pdf](https://github.com/markniu/Bed_Distance_sensor/files/13439492/MKS.Nano6.V3.3_002.PIN.Reborn2.pdf)

![NANO6_3_3pinout](https://github.com/markniu/Bed_Distance_sensor/assets/118969093/1ffb1dd6-4c12-477a-87e6-286fbdac1b11)

Thank you in Advance

**Comment by markniu** [comment]
right, the endstop pin on MKS board normally can't be used for BDsensor.  you can try this: Neopixel(PE7)--->CLK, PA8 -- >SDA

**Comment by yardi83** [comment]
Alright thanks. I will try as soon as bd sensor shows up and report back
