### ISSUE TITLE
Great idea but instructions are unclear

### ISSUE THREAD

**Issue by Zchulski** [markniu/Bed_Distance_sensor#5]
I bought one of these sensors but the directions I think are unclear enough for non linux based user to install klipper without kiauh after about 3 hours of dinking with the klipper install i'm about to give up.  Great idea but unless this get put into the main fork of klipper it is a losing battle i think

**Comment by DarKingF0x** [comment]
The instructions are right there in the Klipper install wiki in this repository.
https://github.com/markniu/Bed_Distance_sensor/wiki/Installing-for-Klipper

**Comment by Zchulski** [comment]
ohh trust i followed them to the letter and am still running to issues. klipper, mainsail, and moonraker just don't seem to want to talk to each other.  I deleted klipper and will be installing again via markniu's isntructions then going to the klipper repo to follow the rest of them

**Comment by Zchulski** [comment]
installed everything according to the directions and still have nothing working correctly mainsail talks to moonraker but moonraker and klipper are not working together

**Comment by Zchulski** [comment]
![image](https://user-images.githubusercontent.com/58801750/220531268-7836db7f-3c8f-4132-b11a-255342636e4e.png)

this is what i have
