### ISSUE TITLE
Unable to calibrate on my Switchwire. 

### ISSUE THREAD

**Issue by Clarkbf** [markniu/Bed_Distance_sensor#51]
Switchwire only moves one stepper so toolhead slides across bed but does not lift when sending M102 S-6 command.

**Comment by markniu** [comment]
you mean only one z stepper moves after sending M102 S-6 and other z steppers don't move?

**Comment by Clarkbf** [comment]
Yes, and very slowly. Wondering if it is a corexz issue? Had no real problems setting it up on my corexy trident.

**Comment by Sakoda1066** [comment]
I'm also SwitchWire, but when performing calibration, the XStepper and ZStepper move in the same direction; with SwitchWire, which is CoreXZ, it just moves the tool head to the right. The correct movement is that the XStepper and ZStepper should turn in opposite directions.
I think the ZStepper is the opposite.

**Comment by Clarkbf** [comment]
I tried inverting wire to Z Stepper and had to Invert pin in Printer.cfg. Still did not work. If I do not invert pin M102 S-6 does work but then cannot home due to print head being slammed into top bar. LOL is there a setting to change in BDsensor.py to change how M102 S-6 works??

**Comment by Clarkbf** [comment]
It is almost like the python script is not pulling the kinematics in properly to move the right steppers. Or inverting the direction of one of them in the calibration process.

**Comment by markniu** [comment]
I just changed the z motor moving with new method(G1 Z), you can update the BDsensor.py and calibrate again.

**Comment by Clarkbf** [comment]
Awesome, will give it a try.

**Comment by Clarkbf** [comment]
Calibrates now but I get this error when it goes to home Z:
 Internal error on command:"G28"
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
Adding my klippy.log

[klippy.log](https://github.com/markniu/Bed_Distance_sensor/files/13655152/klippy.log)

**Comment by Clarkbf** [comment]
Another error that shows up at same time - Unknown value 'PROBE_2' in enumeration 'pin'

***Correction: solved the problem by eliminating my ALIAS PINS for canbus pins.
