### ISSUE TITLE
no_prob_stop not working

### ISSUE THREAD

**Issue by poisson21** [markniu/Bed_Distance_sensor#54]
I have a functioning setup : BDsensor connected to a HermitCrab Can version with a combo BTT py /BTT octopus v1.1.
It work well and i can Z home and map the bed correctly with stop at each control point.

If i try to activate no_stop_prob :
it will do a first mapping without pause
Then restart one from the end of the first one backward
and then at the end stop with an error 'BDProbePointsHelper' object has no attribute 'mcu_probe' .
And so the mapping is not considered at all.

**Comment by markniu** [comment]
could you attatch the klippy.log file?

**Comment by poisson21** [comment]
here it is.
[klippy.log](https://github.com/markniu/Bed_Distance_sensor/files/13661721/klippy.log)

**Comment by markniu** [comment]
did you use the beta version? I just found this bug is in the beta version that caused by the new extra endstop feature  and I just fixed that in the beta version

**Comment by poisson21** [comment]
yes i use the beta version, i will update.

Edit: after a try, no more error, just a double mapping, once it finish the first it start a new one backward, don't know if it is intented like that but the result is a succes.
