### ISSUE TITLE
unable to flash new firmware to SKR3

### ISSUE THREAD

**Issue by Zchulski** [markniu/Bed_Distance_sensor#6]
not sure if this is the the fault of mark here but I am unable to flash the bdsensor firmware to an SKR3.  i keep getting the following error

```
MCU Protocol error

This is frequently caused by running an older version of the
firmware on the MCU(s). Fix by recompiling and flashing the
firmware.

Your Klipper version is: 256a0062-dirty
MCU(s) which should be updated:
mcu: Current version 256a0062-dirty-20230222_064949-mainsail
Up-to-date MCU(s):
<none>

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.

mcu 'mcu': Unknown command: I2C_BD_send
```

update:
it turns out that the MCU did accept the firmware but something doesn't seem to be working correctly.  Does this sensor only work with some specific boards?  Is the SKR 3 not one of these boards? i have also attached a copy of my klippy.log
[klippy.log](https://github.com/markniu/Bed_Distance_sensor/files/10801009/klippy.log)

**Comment by markniu** [comment]
seems that the version of the MCU firmware and the klippy are different. make sure the /home/pi/klipper is download from https://github.com/markniu/klipper-for-pull.git not https://github.com/Klipper3d/klipper

**Comment by Zchulski** [comment]
That's where I got it from, 3 times actually lol.  if you can manage to compile the firmware and attach it in here I will try it then but as of right now no matter how I try to compile the firmware for an skr3 on klipper it doesn't want to seem to work.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by markniu** [comment]
please run command `grep "I2C_BD_send" -r *`in the /home/pi/klipper ,  there should be some I2C_BD_send information out there like this 
![image](https://user-images.githubusercontent.com/13879340/220555138-6c54afbd-05a7-4e17-919e-655f54a944cd.png)

**Comment by Zchulski** [comment]
Will try tomm I swapped out to my working os so I could print something overnight will update tomm afternoon

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by markniu** [comment]
message in the log `mcu 'mcu': Unknown command: I2C_BD_send` means there is no command code` I2C_BD_send` in the python code of pi or firmware in the mcu.
E.g, in the klippy/extras/BDsensor.py  and  BD_sensor.c

**Comment by markniu** [comment]
I think I find the reason of this problem: the klipper will not compile the BDsensor.c into the fimware after we select the STM32H7 (SKR3)and STM32M0 in the `make menuconfig`.

**Comment by Zchulski** [comment]
Do I have to reinstall klipper to get these commits loaded?

**Comment by markniu** [comment]
> Do I have to reinstall klipper to get these commits loaded?

right, just delete the klipper folder and git clone again.

**Comment by Zchulski** [comment]
still no good still getting an error whatever you did was not the fix

```pi@mainsail:~/klipper $ grep I2C_BD_send -r
out/compile_time_request.c:extern void command_I2C_BD_send(uint32_t*);
out/compile_time_request.c:    // I2C_BD_send oid=%c data=%*s
out/compile_time_request.c:    .func=command_I2C_BD_send
grep: out/compile_time_request.o: binary file matches
out/klipper.dict:{"build_versions":"gcc: (15:8-2019-q3-1+b1) 8.3.1 20190703 (release) [gcc-8-branch revision 273027] binutils: (2.35.2-2+14+b2) 2.35.2","commands":{"I2C_BD_receive oid=%c data=%*s":54,"I2C_BD_receive2 oid=%c data=%*s":53,"I2C_BD_send oid=%c data=%*s":52,"allocate_oids count=%c":8,"buttons_ack oid=%c count=%c":61,"buttons_add oid=%c pos=%c pin=%u pull_up=%c":63,"buttons_query oid=%c clock=%u rest_ticks=%u retransmit_count=%c invert=%c":62,"clear_shutdown":2,"config_I2C_BD oid=%c sda_pin=%u scl_pin=%u delay=%u":51,"config_adxl345 oid=%c spi_oid=%c":47,"config_analog_in oid=%c pin=%u":32,"config_buttons oid=%c button_count=%c":64,"config_counter oid=%c pin=%u pull_up=%c":71,"config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u":17,"config_endstop oid=%c pin=%c pull_up=%c":26,"config_hd44780 oid=%c rs_pin=%u e_pin=%u d4_pin=%u d5_pin=%u d6_pin=%u d7_pin=%u delay_ticks=%u":60,"config_neopixel oid=%c pin=%u data_size=%hu bit_max_ticks=%u reset_min_ticks=%u":69,"config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u":43,"config_spi oid=%c pin=%u cs_active_high=%c":38,"config_spi_angle oid=%c spi_oid=%c spi_angle_type=%c":50,"config_spi_shutdown oid=%c spi_oid=%c shutdown_msg=%*s":33,"config_spi_without_cs oid=%c":37,"config_st7920 oid=%c cs_pin=%u sclk_pin=%u sid_pin=%u sync_delay_ticks=%u cmd_delay_ticks=%u":57,"config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u":23,"config_thermocouple oid=%c spi_oid=%c thermocouple_type=%c":40,"config_tmcuart oid=%c rx_pin=%u pull_up=%c tx_pin=%u bit_time=%u":66,"config_trsync oid=%c":30,"debug_nop":9,"debug_ping data=%*s":10,"debug_read order=%c addr=%u":12,"debug_write order=%c addr=%u val=%u":11,"emergency_stop":3,"endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c":25,"endstop_query_state oid=%c":24,"finalize_config crc=%u":6,"get_clock":5,"get_config":7,"get_uptime":4,"hd44780_send_cmds oid=%c cmds=%*s":59,"hd44780_send_data oid=%c data=%*s":58,"identify offset=%u count=%c":1,"neopixel_send oid=%c":67,"neopixel_update oid=%c pos=%hu data=%*s":68,"query_adxl345 oid=%c clock=%u rest_ticks=%u":46,"query_adxl345_status oid=%c":45,"query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u min_value=%hu max_value=%hu range_check_count=%c":31,"query_counter oid=%c clock=%u poll_ticks=%u sample_ticks=%u":70,"query_spi_angle oid=%c clock=%u rest_ticks=%u time_shift=%c":49,"query_thermocouple oid=%c clock=%u rest_ticks=%u min_value=%u max_value=%u max_invalid_count=%c":39,"queue_digital_out oid=%c clock=%u on_ticks=%u":15,"queue_pwm_out oid=%c clock=%u value=%hu":42,"queue_step oid=%c interval=%u count=%hu add=%hi":22,"reset":72,"reset_step_clock oid=%c clock=%u":20,"set_digital_out pin=%u value=%c":13,"set_digital_out_pwm_cycle oid=%c cycle_ticks=%u":16,"set_next_step_dir oid=%c dir=%c":21,"set_pwm_out pin=%u cycle_ticks=%u value=%hu":41,"spi_angle_transfer oid=%c data=%*s":48,"spi_send oid=%c data=%*s":34,"spi_set_bus oid=%c spi_bus=%u mode=%u rate=%u":36,"spi_set_software_bus oid=%c miso_pin=%u mosi_pin=%u sclk_pin=%u mode=%u rate=%u":44,"spi_transfer oid=%c data=%*s":35,"st7920_send_cmds oid=%c cmds=%*s":56,"st7920_send_data oid=%c data=%*s":55,"stepper_get_position oid=%c":19,"stepper_stop_on_trigger oid=%c trsync_oid=%c":18,"tmcuart_send oid=%c write=%*s read=%c":65,"trsync_set_timeout oid=%c clock=%u":28,"trsync_start oid=%c report_clock=%u report_ticks=%u expire_reason=%c":29,"trsync_trigger oid=%c reason=%c":27,"update_digital_out oid=%c value=%c":14},"config":{"ADC_MAX":4095,"BUS_PINS_spi1":"PA6,PA7,PA5","BUS_PINS_spi1a":"PB4,PB5,PB3","BUS_PINS_spi2":"PB14,PB15,PB13","BUS_PINS_spi2a":"PC2,PC3,PB10","BUS_PINS_spi2b":"PI2,PI3,PI1","BUS_PINS_spi3a":"PC11,PC12,PC10","BUS_PINS_spi4":"PE13,PE14,PE12","BUS_PINS_spi5":"PF8,PF9,PF7","BUS_PINS_spi5a":"PH7,PF11,PH6","BUS_PINS_spi6":"PG12,PG14,PG13","CLOCK_FREQ":400000000,"MCU":"stm32h743xx","PWM_MAX":255,"RESERVE_PINS_USB":"PA11,PA12","RESERVE_PINS_crystal":"PH0,PH1","STATS_SUMSQ_BASE":256,"STEPPER_BOTH_EDGE":1},"enumerations":{"pin":{"ADC_TEMPERATURE":254,"PA0":[0,16],"PB0":[16,16],"PC0":[32,16],"PD0":[48,16],"PE0":[64,16],"PF0":[80,16],"PG0":[96,16],"PH0":[112,16],"PI0":[128,16]},"spi_angle_type":{"a1333":0,"as5047d":1,"tle5012b":2},"spi_bus":{"spi1":1,"spi1a":2,"spi2":0,"spi2a":3,"spi2b":6,"spi3a":4,"spi4":5,"spi5":7,"spi5a":8,"spi6":9},"static_string_id":{"ADC out of range":26,"Already finalized":13,"Can not set soft pwm cycle ticks while updates pending":20,"Can't add signal that is already active":25,"Can't assign oid":11,"Can't reset time when stepper active":22,"Command parser error":7,"Command request":8,"Invalid PWM channel":45,"Invalid buttons retransmit count":34,"Invalid command":5,"Invalid count parameter":23,"Invalid move request size":14,"Invalid neopixel data_size":39,"Invalid neopixel update command":38,"Invalid oid type":12,"Invalid spi bus":44,"Invalid spi config":27,"Invalid spi_angle chip type":33,"Invalid thermocouple chip type":29,"Max of 8 buttons":36,"Message encode error":6,"Missed scheduling of next digital out event":21,"Missed scheduling of next hard pwm event":31,"Move queue overflow":15,"Not a valid ADC pin":43,"Not a valid PWM pin":47,"Not a valid input pin":40,"Not an output pin":41,"PWM already programmed at different speed":46,"Rescheduled timer in the past":42,"Scheduled digital out event will exceed max_duration":19,"Scheduled pwm event will exceed max_duration":30,"Set button past maximum button count":35,"Shutdown cleared when not shutdown":2,"Stepper too far in past":24,"Thermocouple reader fault":28,"Timer too close":3,"alloc_chunk failed":17,"alloc_chunks failed":16,"angle sensor requires cs pin":32,"config_reset only available when shutdown":9,"oids already allocated":10,"sentinel timer called":4,"tmcuart data too large":37,"update_digital_out not valid with active queue":18},"thermocouple_type":{"MAX31855":0,"MAX31856":1,"MAX31865":2,"MAX6675":3}},"responses":{"I2C_BD_receive2_response oid=%c response=%*s":93,"I2C_BD_receive_response oid=%c response=%*s":94,"adxl345_data oid=%c sequence=%hu data=%*s":89,"adxl345_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%c fifo=%c limit_count=%hu":88,"analog_in_state oid=%c next_clock=%u value=%hu":85,"buttons_state oid=%c ack_count=%c state=%*s":95,"clock clock=%u":78,"config is_config=%c crc=%u is_shutdown=%c move_count=%hu":79,"counter_state oid=%c next_clock=%u count=%u count_clock=%u":-30,"debug_result val=%u":81,"endstop_state oid=%c homing=%c next_clock=%u pin_value=%c":83,"identify_response offset=%u data=%.*s":0,"is_shutdown static_string_id=%hu":74,"neopixel_result oid=%c success=%c":-31,"pong data=%*s":80,"shutdown clock=%u static_string_id=%hu":75,"spi_angle_data oid=%c sequence=%hu data=%*s":92,"spi_angle_end oid=%c sequence=%hu":91,"spi_angle_transfer_response oid=%c clock=%u response=%*s":90,"spi_transfer_response oid=%c response=%*s":86,"starting":73,"stats count=%u sum=%u sumsq=%u":76,"stepper_position oid=%c pos=%i":82,"thermocouple_result oid=%c next_clock=%u value=%u fault=%c":87,"tmcuart_response oid=%c read=%*s":-32,"trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u":84,"uptime high=%u clock=%u":77},"version":"26b6335b-dirty-20230223_214000-mainsail"}
out/compile_time_request.txt:DECL_COMMAND_FLAGS command_I2C_BD_send 0 I2C_BD_send oid=%c data=%*s
grep: out/src/BD_sensor.o.ctr: binary file matches
grep: out/src/BD_sensor.o: binary file matches
grep: out/klipper.elf: binary file matches
src/BD_sensor.c:command_I2C_BD_send(uint32_t *args)
src/BD_sensor.c:DECL_COMMAND(command_I2C_BD_send, "I2C_BD_send oid=%c data=%*s");
grep: klippy/extras/BDsensor.pyc: binary file matches
klippy/extras/BDsensor.py:        self.I2C_BD_send_cmd = self.I2C_BD_receive_cmd = None
klippy/extras/BDsensor.py:        self.I2C_BD_send_cmd = self.mcu.lookup_command(
klippy/extras/BDsensor.py:            "I2C_BD_send oid=%c data=%*s", cq=self.cmd_queue)
klippy/extras/BDsensor.py:    def I2C_BD_send(self, data):
klippy/extras/BDsensor.py:        self.I2C_BD_send_cmd.send([self.oid, data])
klippy/extras/BDsensor.py:                    self.bd_sensor.I2C_BD_send("1019")
klippy/extras/BDsensor.py:                        self.bd_sensor.I2C_BD_send(str(ncount))
klippy/extras/BDsensor.py:                        self.bd_sensor.I2C_BD_send(str(ncount))
klippy/extras/BDsensor.py:                            self.bd_sensor.I2C_BD_send("1021")
klippy/extras/BDsensor.py:            self.bd_sensor.I2C_BD_send("1017")#tart read raw calibrate data
klippy/extras/BDsensor.py:            self.bd_sensor.I2C_BD_send("1016")#1016 // // read sensor version
klippy/extras/BDsensor.py:                    self.bd_sensor.I2C_BD_send("1018")#1018// finish reading
klippy/extras/BDsensor.py:            self.bd_sensor.I2C_BD_send("1015")#1015   read distance data
klippy/extras/BDsensor.py:        self.bd_sensor.I2C_BD_send("1018")
klippy/extras/BDsensor.py:       # self.bd_sensor.I2C_BD_send("890")
grep: klippy/extras/probe.pyc: binary file matches
klippy/extras/probe.py:        self.I2C_BD_send_cmd3 = None
klippy/extras/probe.py:            self.I2C_BD_send_cmd3 = self.mcu.lookup_command(
klippy/extras/probe.py:                "I2C_BD_send oid=%c data=%*s", cq=self.cmd_queue)
klippy/extras/probe.py:        if probe.I2C_BD_send_cmd3 is not None:
klippy/extras/probe.py:            probe.I2C_BD_send_cmd3.send([probe.oid, "1022"])
klippy/extras/probe.py:        if probe.I2C_BD_send_cmd3 is not None:
klippy/extras/probe.py:            probe.I2C_BD_send_cmd3.send([probe.oid, "1018"])
pi@mainsail:~/klipper $
```

**Comment by Zchulski** [comment]
Ok I finally got the sensor to communicate correctly but I think there is some kind of problem.  The raw data coming from the sensor isn't matching what i'm seeing in real life I can touch the sensor to the bed and i'm still getting 511 on the raw data.  The numbers im mainly seeing is somewhere between 900 and 500 and it doesnt matter what the distance the sensor is from the bed I still get the same numbers which doesn't seem right.  And I cant move the z axis without it and i cant calibrate it without having the sensor work.  so i might be between a rock and a hard spot with this sensor.  are these values im seeing supposed to be correct

**Comment by markniu** [comment]
how about the value of distance after sending `M102   S-2`  ? 
If the raw calibration data after` M102 M-5 `are continue increased within 0 - 1000 that means the sensor works, but all that raw data were from the last calibration before the sensor was shipped out.  
you can move down the nozzle close to the bed by moving the z motor with hand before sending `M102 M-5` while printer is power off.

**Comment by Zchulski** [comment]
What I'm failing to understand here is what exactly is the difference between s2 and s5? It doesn't matter if the sensor Is 1mm from the bed or touching the bed I still get the same value from the sensor

**Comment by Zchulski** [comment]
I either get 511 or 1024 doesn't matter how far the sensor is from the bed with m102 s-2

**Comment by markniu** [comment]
Could you paste some data after M102 S-5 here? for example the first 10 data.

**Comment by Zchulski** [comment]
![image](https://user-images.githubusercontent.com/58801750/221072445-7e179fcd-0b1b-4668-97f3-bdf197cd9070.png)

**Comment by Zchulski** [comment]
i'm also seeing another issue when you run M102 S-6 only one of my z stepper motors is actually driving the moving.  I have a dual Z setup so both of those steppers should be driving the Z axis not just one of them

**Comment by Zchulski** [comment]
tried homing the machine and crashed my head so thanks for that

**Comment by Zchulski** [comment]
![20230223_205903.jpg](https://user-images.githubusercontent.com/58801750/221073499-baaa95b1-0773-4be3-a8ee-ba12b6f8ee56.jpg)

Raw data from this picture is saying 1024 according to your graph that number can't be correct

**Comment by markniu** [comment]
and I also find that the frequency of processer stm32H743 is 480 MHz that is much higher than stm32f103(72MHz) which I used, so you can adjust the delay value from 800000 to 4800000 and then get the data again.

**Comment by Zchulski** [comment]
1024 is the only number I get now

**Comment by Zchulski** [comment]
> and I also find that the frequency of processer stm32H743 is 480 MHz that is much higher than stm32f103(72MHz) which I used, so you can adjust the delay value from 800000 to 4800000 and then get the data again.

You also are gonna need to fix the dual stepper issue as well I can't calibrate this if both my steppers arnt working

**Comment by markniu** [comment]
the sensor has erased all the calibrate data in memory after sending M102 S-6 and will write the new calibrate in after finishing calibration.  if the sensor is out the sensor range while calibrate or power off printer without finish, all the data will be 1024
so you need to calibrate again.

**Comment by markniu** [comment]
> > and I also find that the frequency of processer stm32H743 is 480 MHz that is much higher than stm32f103(72MHz) which I used, so you can adjust the delay value from 800000 to 4800000 and then get the data again.
> 
> You also are gonna need to fix the dual stepper issue as well I can't calibrate this if both my steppers arnt working

Oh, Thanks for feedback this, I will fix this as soon as possible.

**Comment by Zchulski** [comment]
As of right now with this sensor I'm getting nothing but a value of 1024 with m102 s2 and s5

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by ptegler** [comment]
> tried homing the machine and crashed my head so thanks for that

why would you try to zero when your sensor wasn't working to begin with? hhmmm well... why are you trying to run a forked klipper that would get over written the first time klipper updates?  markniu...are you configuring along with mainsail, moonraker etc?   I have had this sensor in hand for a month+ now....have not even tried to use it until Klipper accepts it into the main app

**Comment by Zchulski** [comment]
> > tried homing the machine and crashed my head so thanks for that
> 
> why would you try to zero when your sensor wasn't working to begin with? hhmmm well... why are you trying to run a forked klipper that would get over written the first time klipper updates? markniu...are you configuring along with mainsail, moonraker etc? I have had this sensor in hand for a month+ now....have not even tried to use it until Klipper accepts it into the main app

according to mark the sensor is working just not in a real world application.  Also klipper won't update with the forked version, it says its dirty and you can't even do a hard reset on klipper.  I'm running the forked version on a separate SD card so when I need to use the printer I can just swap out SD cards.  I don't see this getting implemented into the main fork until he gets alot more kinks worked out of it.  for instance the dual stepper issue i'm running into, and who knows how many other boards are not gonna be supported right out of the box like mine wasn't.  Props for getting that fixed in a reasonable amount of time. 

i'm not entirely sure what the issue with my sensor is but it was driving me bonkers so I gave up for the night it just isn't registering anything from the bed.  I know the distance from the nozzle to probe is reasonably good because I made a mount for it in solidworks.

**Comment by Zchulski** [comment]
re-downloaded the fork of klipper and now the dual z axis is working but I am still unable to get the sensor to calibrate.  It doesn't matter the distance to the bed the nozzle and probe are from the bed I am still getting a return of 1024 on the M102 commands.  Either my sensor is busted or this isn't going to work for me.  im seriously about to give up on this en devour in klipper. @markniu if you have any other ideas shoot them over to me I will keep trying but I don't know if this is going to work with this sensor

**Comment by Zchulski** [comment]
@markniu 

I found part of my problem,  being that my clk and sda pin were configured incorrectly once that was fixed some of the above issues were fixing but i'm still having issues calibrating.  my calibration numbers are anywhere between 1024 and 511 on a single calibration.  whatever is going on here is getting weirder by the day.  Can you maybe put something in your klipper fork making klipper error out if the pins are configured backwards may help out new players here.  what else can i do to fix the calibration issues

**Comment by markniu** [comment]
> @markniu
> 
> I found part of my problem, being that my clk and sda pin were configured incorrectly once that was fixed some of the above issues were fixing but i'm still having issues calibrating. my calibration numbers are anywhere between 1024 and 511 on a single calibration. whatever is going on here is getting weirder by the day. Can you maybe put something in your klipper fork making klipper error out if the pins are configured backwards may help out new players here. what else can i do to fix the calibration issues

adding some error message out is good idea.  I have fixed the problem about only one z axis works while calibration, you can update the code from the fork.
