### ISSUE TITLE
Internal Error on "BDSENSOR_READ_CALIBRATION"

### ISSUE THREAD

**Issue by DavidCarl** [markniu/Bed_Distance_sensor#63]
Hello

I followed the klipper installation guide, and when I try to run the command "BDSENSOR_READ_CALIBRATION", klipper chrashes....

```
Reactor garbage collection: (160.273363242, 0.0, 0.0)
Internal error on command:"BDSENSOR_READ_CALIBRATION"
Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/webhooks.py", line 256, in _process_request
    func(web_request)
  File "/home/biqu/klipper/klippy/webhooks.py", line 436, in _handle_script
    self.gcode.run_script(web_request.get_str('script'))
  File "/home/biqu/klipper/klippy/gcode.py", line 229, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/biqu/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/biqu/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/biqu/klipper/klippy/extras/BDsensor.py", line 994, in BD_read_calibration
    raise self.printer.command_error("BDSensor mounted too close or too high!" % intd)
TypeError: not all arguments converted during string formatting
MCU 'rpi' shutdown: Command request
```

I have attached my whole Klippy log (its a long one).

Another issue I am having is when I try to home my printer it just chrashes the nozzle into the bed.

Sincerely
David Carl

[klippy(3).log](https://github.com/markniu/Bed_Distance_sensor/files/13756653/klippy.3.log)

**Comment by markniu** [comment]
This error means that it detected the first point in calibration data is too large(1015) by command M102 S-5,
it happens in calibration when the distance of coil to bed is below the 0.4mm or higher than 4mm
you can check it by keeping the coil to bed about 1mm and calibrate it again

this should be same as #62
