### ISSUE TITLE
Klipper gives "internal error" in MKS Robin Nano v3

### ISSUE THREAD

**Issue by proturka** [markniu/Bed_Distance_sensor#7]
I bought your excellent precise distance sensor and i tried in arduino -which uses serial i2c- Its working very well as you documented.

But when i tried to connect to use with klipper -to board MKS Robin Nano v3- after i send M102 S-1 command, klipper gives internal error. And i think this issue is related to connection with the board.

I did every single step in this document, including printer.cfg: https://github.com/markniu/Bed_Distance_sensor/wiki/Installing-for-Klipper

I also compiled klipper with your repo and updated board's firmware without any issue.

I searched for the connection necessities in your documents (github readme, issues and wiki) but no results

I tried 2 different pin config. I used board's 5V / GND pins. and for the data pins, i used PB10/PB11 and PD10/PD11 as sda/scl but both didnt gave any results.

Any clue about what i am missing?

This is klipper log:

Internal error on command:"M102"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/BDsensor.py", line 216, in cmd_M102
    self.bd_sensor.I2C_BD_send("1015")#1015   read distance data
  File "/home/pi/klipper/klippy/extras/BDsensor.py", line 56, in I2C_BD_send
    self.I2C_BD_send_cmd.send([self.oid, data])
  File "/home/pi/klipper/klippy/mcu.py", line 530, in send
    cmd = self._cmd.encode(data)
  File "/home/pi/klipper/klippy/msgproto.py", line 175, in encode
    t.encode(out, params[i])
  File "/home/pi/klipper/klippy/msgproto.py", line 78, in encode
    out.extend(bytearray(v))
TypeError: string argument without an encoding
Transition to shutdown state: Internal error on command:"M102"

**Comment by markniu** [comment]
I have not met this error on my pi3, but you can try this way to fix:
run `nano /home/pi/klipper/klippy/msgproto.py `
and find the line 78 and change the `out.extend(bytearray(v))` to `out.extend(bytearray(v, 'utf8'))`
reference to this https://stackoverflow.com/questions/31161243/python-string-argument-without-an-encoding

**Comment by proturka** [comment]
I tried it but no change. 

But after i downgrade python version to 2, it worked like a charm. 

but now sensor only shows 1024. rarely gave 835 / 1023, but mostly 1024 only.

**Comment by markniu** [comment]
What's the data returned after send command M102 S-1 and M102 S-5

**Comment by proturka** [comment]
M102 S-1 "" (non visible chars)
M102 S-5 shows many 1024s

**Comment by markniu** [comment]
there should be some text string after M-1. it seems there is communicating problem, I think need to increase the delay value in the configuration file, I will test it with octopus board that MCU is also STM32F4

**Comment by proturka** [comment]
when i increased delay to 1600000 it kinda worked. 

M102 S-1 output is: "1 pandapdm"


when i increased to 1700000 same non visible chars, 2000000 is same.

when i set value to 1500000 it outputs "V1.0 pandapi3d.com". i think it is the best value for delay. it worked very well

thank you for your response. 

product is great. 

now i will test on real print soon. 

one last question, is it possible to use it as z end stop? or it is aligns only while printing with applying babysteps?

**Comment by markniu** [comment]
that's great. it is only used as end stop while homing z axis.

**Comment by proturka** [comment]
It is still unstable. Sometime it needs fully restart to delay setting change be applied. I am trying to find stable setting for delay, but i got no result yet. 

And M102 S-5 is starts from ~900 . In your documents it should start with ~0-75 as i can see. 
 
Is there any setting to make it work right, or i should wait more stable version for klipper?. I am not choosing marlin because there is huge quality gap, klipper is much better. 

Or i should calibrate it with your tool with marlin, and then start to use this calibration setting with klipper?

**Comment by proturka** [comment]
I tried various distances. I even tried equal distance (almost). But i will check again and inform you about it. 

I have a related question. Is m102 s-2 gives relative result with calibration? Or it is absolute value from sensor?

**Comment by proturka** [comment]
I tried various distances. I even tried equal distance (almost). But i will check again and inform you about it. 

I have a related question. Is m102 s-2 gives relative result with calibration? Or it is absolute value from sensor?

**Comment by markniu** [comment]
M102 S-2 gives absolute value from sensor but need to *0.01. for example, if it returns 435 that means 4.35mm
I think I should change the source code that let it return 4.35mm instead of 435.

**Comment by proturka** [comment]
Then i can say, m102 s-2 gives correct values always. Relative with klipper’s z coordinate. 

Why there is difference between those? If you need some logs or spesific tests for it, i can provide

**Comment by markniu** [comment]
the data after command M102 S-5 are calibration raw data, the sensor will get a new raw data at every distance and then it can calculate the actual distance value based on the calibration raw data.
the octopuls board is out of stock in my local market so I just placed a new order of board MKS robin V3 hope I can get it 2 days later.

**Comment by neshami** [comment]
> I have not met this error on my pi3, but you can try this way to fix:
run nano /home/pi/klipper/klippy/msgproto.py 
and find the line 78 and change the out.extend(bytearray(v)) to out.extend(bytearray(v, 'utf8'))
reference to this https://stackoverflow.com/questions/31161243/python-string-argument-without-an-encoding

At least, after this edit finaly works as expected.

**Comment by markniu** [comment]
Just update this tutorial :  https://github.com/markniu/Bed_Distance_sensor/wiki/Installing-for-Klipper
and also please update the sourcecode that fixed one communication bug for stm32f407 
![image](https://user-images.githubusercontent.com/13879340/224550790-d68ee507-4e00-4603-85f1-5367107b72c1.png)
![image](https://user-images.githubusercontent.com/13879340/224550833-3153a57f-7bdf-4e7e-bcf4-8bf756dc51a1.png)

**Comment by markniu** [comment]
I also found the PA5 in the board MKS_RobinNanoV3 cannot be use as sda_pin because it works as other fuction in the bootloader that send a lot of signals while booting that let the BDsensor worked as unusual.

**Comment by proturka** [comment]
I tried with updated source code now, but still same. calibration values starts with 900+. m102 s-2 is working well, fast and precised. but calibration is not. 

Do you have any suggestion to try?

**Comment by proturka** [comment]
M102 S-2 shows 2.3mm only. And this is the photo of distance between nozle:

![F0189E33-4A15-4DB7-A541-EEDF88978EEA](https://user-images.githubusercontent.com/92768106/225620447-596d28b0-e621-4af9-a957-cf24a93959f9.jpeg)

**Comment by markniu** [comment]
that's close enough, and do calibrated again,if still problem send the first 10 calibration data give by M102 S-5 here

**Comment by proturka** [comment]
Here the file. same thing happened. M102 S-1 and S-2 works well.

<img width="1329" alt="Screen Shot 2023-03-16 at 17 59 49" src="https://user-images.githubusercontent.com/92768106/225641046-3e5614a8-c4f5-42f7-a19f-3b6fd90fad45.png">

**Comment by markniu** [comment]
is it a glass bed? Put one metal like thin knife close to the sensor instead of your bed, and do a calibrate again.

**Comment by proturka** [comment]
its acrylic glass but on the top, there is aliminum plate. sensor able to detect it. 

but i will try calibration with knife or similar metal

**Comment by proturka** [comment]
I did the test, and this is the result.

<img width="1790" alt="Screen Shot 2023-03-17 at 10 51 19" src="https://user-images.githubusercontent.com/92768106/225833416-d5e4f90e-83b8-489b-880d-49648fe82144.png">

It looks like no change. idk what is the problem. I kept knife in zero distance with sensor

**Comment by markniu** [comment]
> I did the test, and this is the result.
> 
> <img alt="Screen Shot 2023-03-17 at 10 51 19" width="1790" src="https://user-images.githubusercontent.com/92768106/225833416-d5e4f90e-83b8-489b-880d-49648fe82144.png">
> 
> It looks like no change. idk what is the problem. I kept knife in zero distance with sensor

not sure what's the problem, could you send me your order number? I will send a new one to you.

**Comment by proturka** [comment]
order number is 10350. thank you for your support
