### ISSUE TITLE
QUAD_GANTRY_LEVEL 

### ISSUE THREAD

**Issue by davidsiaw** [markniu/Bed_Distance_sensor#77]
I am having the same issue as https://github.com/markniu/Bed_Distance_sensor/issues/37  but Z_TILT adjust cannot be done because I am using a flying gantry. I use the bdsensor on the CAN toolhead on the BLtouch probe. EBB42.

<img width="403" alt="スクリーンショット 2024-01-17 1 30 17" src="https://github.com/markniu/Bed_Distance_sensor/assets/874280/d0ed2b93-ec5a-4fac-9583-87a6f7f0d8e6">

The gantry can sink more than 2-3mm , so the BD sensor needs to hop. Setting the horizontal movement z is too close and will damage the bed. 

I cannot do quad gantry levelling with BDSensor because of this. Can you please help me?

Is there a way to make the QGL hop like a normal probe? 

(edit)
I managed to make it Z-tilt but whenever it moves up and then moves down to detect the bed, it shows communication timeout, and then after a delay it says triggered at 0.0mm, then it just stops doing Z-tilt.

I tried to increase the timeout in the code (TRSYNC_TIMEOUT), and it started hopping once or twice and then stops again, and  then starts to timeout and then triggered at 0.0mm as above.

I noticed that when the BDsensor is connected it gets slower and slower. When you start it up first and say M102 S-1 it returns  "V1.0 pandapi3d.com" immediately. But after using it for a while when you say M102 S-1 it takes almost 1 minute to respond. After some time things slow down like crazy, and the CAN toolhead stops responding.

**Comment by markniu** [comment]
Hello, there is a update from klipper yesterday that may fix your timeout problem. please update the BDsensor.py and klipper, try again.

if you want to increase the homing timeout `TRSYNC_TIMEOUT `please modify the `TRSYNC_TIMEOUT `in the BDsensor.py.

**Comment by davidsiaw** [comment]
@markniu thank you for your reply! Can you tell me how to make QGL hop like the inductive sensor? the horizontal move is too close to the bed

**Comment by markniu** [comment]
https://github.com/markniu/Bed_Distance_sensor/issues/74#issuecomment-1895468696

> @markniu thank you for your reply! Can you tell me how to make QGL hop like the inductive sensor? the horizontal move is too close to the bed

**Comment by davidsiaw** [comment]
i will try it later i put my inductor probe back because i need the printer to work. Thank you 🙏
