### ISSUE TITLE
On M102 command printer shutsdown

### ISSUE THREAD

**Issue by neshami** [markniu/Bed_Distance_sensor#8]
When I send M102 command kliiper shuts down with message "Internal error on command:"M102"".
Creality board with STM32F103 for Ender 3S1 printer.
[klippy.log](https://github.com/markniu/Bed_Distance_sensor/files/10948333/klippy.log)

**Comment by proturka** [comment]
Install klipper with python 2. It fixes problem. Same happened to me before.

**Comment by neshami** [comment]
Can you send me message wit how to install with phyton 2?
Thanks in advance.

**Comment by proturka** [comment]
I installed klipper with kiauh tool, and while install it asking python version. I tried 2 instead 3 and it worked normal.

**Comment by neshami** [comment]
Klipper reports: ERROR

Option 'position_endstop' in section 'stepper_z' must be specified

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

**Comment by neshami** [comment]
Unknown command:"M102"

**Comment by neshami** [comment]
With latest git klipper for pull when compile firmware in firmware. bin is`t included BDsensor.o.
Response is as in my previous message. 
Unknown command:"M102"
It happens if I compile firmware in klipper and kliper-for-pull folder.

**Comment by proturka** [comment]
did you select custom repository? kiauh is picking original klipper github as repo source. need to change it from kiauh settings first. then need to compile and -if necessary- flash  the board again.

**Comment by neshami** [comment]
Internal error on command:"M102"
Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/webhooks.py", line 256, in _process_request
    func(web_request)
  File "/home/pi/klipper/klippy/webhooks.py", line 425, in _handle_script
    self.gcode.run_script(web_request.get_str('script'))
  File "/home/pi/klipper/klippy/gcode.py", line 216, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/BDsensor.py", line 196, in cmd_M102
    self.bd_sensor.I2C_BD_send("1016")#1016 // // read sensor version
  File "/home/pi/klipper/klippy/extras/BDsensor.py", line 56, in I2C_BD_send
    self.I2C_BD_send_cmd.send([self.oid, data])
  File "/home/pi/klipper/klippy/mcu.py", line 530, in send
    cmd = self._cmd.encode(data)
  File "/home/pi/klipper/klippy/msgproto.py", line 175, in encode
    t.encode(out, params[i])
  File "/home/pi/klipper/klippy/msgproto.py", line 78, in encode
    out.extend(bytearray(v))
TypeError: string argument without an encoding
MCU 'mcu' shutdown: Command request
clocksync state: mcu_freq=72000000 last_clock=4646036940 clock_est=(603.610 2829914922 71999358.209) min_half_rtt=0.000733 min_rtt_time=589.449 time_avg=603.609(413.426) clock_avg=2829914922.417(29766415415.715) pred_variance=497473376.934
Dumping serial stats: bytes_write=1484 bytes_read=14489 bytes_retransmit=9 bytes_invalid=0 send_seq=188 receive_seq=188 retransmit_seq=2 srtt=0.003 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0
Dumping send queue 100 messages
Sent 0 566.360553 566.360313 6: seq: 18, get_uptime
Sent 1 566.415440 566.415200 6: seq: 19, get_clock
Sent 2 566.469471 566.469231 6: seq: 1a, get_clock
Sent 3 566.523405 566.523165 6: seq: 1b, get_clock
Sent 4 566.577503 566.577263 6: seq: 1c, get_clock
Sent 5 566.631916 566.631676 6: seq: 1d, get_clock
Sent 6 566.686092 566.685852 6: seq: 1e, get_clock
Sent 7 566.740324 566.740084 6: seq: 1f, get_clock
Sent 8 566.794369 566.794129 6: seq: 10, get_clock
Sent 9 566.800646 566.800406 6: seq: 11, get_config
Sent 10 566.800951 566.800711 6: seq: 12, get_clock
Sent 11 566.810955 566.810675 7: seq: 13, allocate_oids count=22
Sent 12 566.811351 566.810991 9: seq: 14, config_endstop oid=0 pin=PC14 pull_up=2
Sent 13 566.811631 566.811233 7: seq: 15, config_trsync oid=1
Sent 14 566.812151 566.811527 13: seq: 16, config_I2C_BD oid=3 sda_pin=PC14 scl_pin=PC13 delay=1800000
Sent 15 566.812591 566.811812 11: seq: 17, config_digital_out oid=13 pin=PA0 value=0 default_value=0 max_duration=0
Sent 16 566.812991 566.812065 10: seq: 18, set_digital_out_pwm_cycle oid=13 cycle_ticks=720000
Sent 17 566.813431 566.812341 11: seq: 19, config_digital_out oid=14 pin=PC0 value=0 default_value=0 max_duration=0
Sent 18 566.813831 566.812587 10: seq: 1a, set_digital_out_pwm_cycle oid=14 cycle_ticks=720000
Sent 19 566.814151 566.812830 8: seq: 1b, config_analog_in oid=15 pin=PC4
Sent 20 566.814751 566.813114 15: seq: 1c, config_digital_out oid=16 pin=PA7 value=0 default_value=0 max_duration=360000000
Sent 21 566.815191 566.813343 11: seq: 1d, set_digital_out_pwm_cycle oid=16 cycle_ticks=7200000
Sent 22 566.815511 566.813562 8: seq: 1e, config_buttons oid=17 button_count=1
Sent 23 566.816631 566.814181 28: seq: 1f, config_analog_in oid=18 pin=ADC_TEMPERATURE, config_stepper oid=5 step_pin=PC2 dir_pin=PB9 invert_step=0 step_pulse_ticks=144, config_digital_out oid=19 pin=PC3 value=1 default_value=1 max_duration=0, config_endstop oid=6 pin=PA5 pull_up=1, config_trsync oid=7
Sent 24 566.817111 566.814411 12: seq: 10, config_stepper oid=8 step_pin=PB8 dir_pin=PB7 invert_step=0 step_pulse_ticks=144
Sent 25 566.817471 566.814643 9: seq: 11, config_endstop oid=9 pin=PA6 pull_up=1
Sent 26 566.817751 566.814850 7: seq: 12, config_trsync oid=10
Sent 27 566.818231 566.815105 12: seq: 13, config_stepper oid=11 step_pin=PB6 dir_pin=PB5 invert_step=0 step_pulse_ticks=144
Sent 28 566.820271 566.817508 51: seq: 14, config_analog_in oid=20 pin=PC5, config_digital_out oid=21 pin=PA1 value=0 default_value=0 max_duration=360000000, set_digital_out_pwm_cycle oid=21 cycle_ticks=7200000, config_stepper oid=12 step_pin=PB4 dir_pin=PB3 invert_step=0 step_pulse_ticks=144, finalize_config crc=3442363115, queue_digital_out oid=13 clock=194366491 on_ticks=0, queue_digital_out oid=14 clock=194378373 on_ticks=0
Sent 29 566.822311 566.817508 51: seq: 15, query_analog_in oid=15 clock=226800000 sample_ticks=72000 sample_count=8 rest_ticks=21600000 min_value=18817 max_value=32303 range_check_count=4, queue_digital_out oid=16 clock=194396452 on_ticks=0, buttons_add oid=17 pos=0 pin=PC15 pull_up=0, buttons_query oid=17 clock=300240000 rest_ticks=144000 retransmit_count=50 invert=1
Sent 30 566.824511 566.821137 55: seq: 16, query_analog_in oid=18 clock=300960000 sample_ticks=72000 sample_count=8 rest_ticks=21600000 min_value=10994 max_value=15264 range_check_count=4, query_analog_in oid=20 clock=302400000 sample_ticks=72000 sample_count=8 rest_ticks=21600000 min_value=731 max_value=32303 range_check_count=4, queue_digital_out oid=21 clock=194565598 on_ticks=0, get_config
Sent 31 566.842588 566.842308 7: seq: 17, stepper_get_position oid=5
Sent 32 566.847286 566.847006 7: seq: 18, stepper_get_position oid=8
Sent 33 566.851383 566.851103 7: seq: 19, stepper_get_position oid=11
Sent 34 566.855097 566.854817 7: seq: 1a, stepper_get_position oid=12
Sent 35 567.785637 567.785397 6: seq: 1b, get_clock
Sent 36 568.480479 568.480159 8: seq: 1c, buttons_ack oid=17 count=1
Sent 37 568.770109 568.769869 6: seq: 1d, get_clock
Sent 38 569.755198 569.754958 6: seq: 1e, get_clock
Sent 39 570.740325 570.740085 6: seq: 1f, get_clock
Sent 40 571.724703 571.724463 6: seq: 10, get_clock
Sent 41 572.709176 572.708936 6: seq: 11, get_clock
Sent 42 573.693212 573.692972 6: seq: 12, get_clock
Sent 43 574.677402 574.677162 6: seq: 13, get_clock
Sent 44 575.661490 575.661250 6: seq: 14, get_clock
Sent 45 576.646080 576.645840 6: seq: 15, get_clock
Sent 46 577.630458 577.630218 6: seq: 16, get_clock
Sent 47 578.615098 578.614858 6: seq: 17, get_clock
Sent 48 579.600243 579.600003 6: seq: 18, get_clock
Sent 49 580.585349 580.585109 6: seq: 19, get_clock
Sent 50 581.569858 581.569618 6: seq: 1a, get_clock
Sent 51 582.555006 582.554766 6: seq: 1b, get_clock
Sent 52 583.539323 583.539083 6: seq: 1c, get_clock
Sent 53 584.523933 584.523693 6: seq: 1d, get_clock
Sent 54 585.508952 585.508712 6: seq: 1e, get_clock
Sent 55 586.494802 586.494562 6: seq: 1f, get_clock
Sent 56 587.479234 587.478994 6: seq: 10, get_clock
Sent 57 588.463923 588.463683 6: seq: 11, get_clock
Sent 58 589.449076 589.448836 6: seq: 12, get_clock
Sent 59 590.434283 590.434043 6: seq: 13, get_clock
Sent 60 591.419463 591.419223 6: seq: 14, get_clock
Sent 61 592.403783 592.403543 6: seq: 15, get_clock
Sent 62 593.388458 593.388218 6: seq: 16, get_clock
Sent 63 594.372999 594.372759 6: seq: 17, get_clock
Sent 64 595.357183 595.356943 6: seq: 18, get_clock
Sent 65 596.341655 596.341415 6: seq: 19, get_clock
Sent 66 597.326323 597.326083 6: seq: 1a, get_clock
Sent 67 598.310625 598.310385 6: seq: 1b, get_clock
Sent 68 599.295099 599.294859 6: seq: 1c, get_clock
Sent 69 600.279559 600.279319 6: seq: 1d, get_clock
Sent 70 601.263896 601.263656 6: seq: 1e, get_clock
Sent 71 602.248253 602.248013 6: seq: 1f, get_clock
Sent 72 603.233014 603.232774 6: seq: 10, get_clock
Sent 73 604.217574 604.217334 6: seq: 11, get_clock
Sent 74 605.202790 605.202550 6: seq: 12, get_clock
Sent 75 606.187421 606.187181 6: seq: 13, get_clock
Sent 76 607.172099 607.171859 6: seq: 14, get_clock
Sent 77 608.156305 608.156065 6: seq: 15, get_clock
Sent 78 609.141061 609.140821 6: seq: 16, get_clock
Sent 79 610.125463 610.125223 6: seq: 17, get_clock
Sent 80 611.110470 611.110230 6: seq: 18, get_clock
Sent 81 612.094725 612.094485 6: seq: 19, get_clock
Sent 82 613.078835 613.078595 6: seq: 1a, get_clock
Sent 83 614.063691 614.063451 6: seq: 1b, get_clock
Sent 84 615.048629 615.048389 6: seq: 1c, get_clock
Sent 85 616.033641 616.033401 6: seq: 1d, get_clock
Sent 86 617.017980 617.017740 6: seq: 1e, get_clock
Sent 87 618.002264 618.002024 6: seq: 1f, get_clock
Sent 88 618.987335 618.987095 6: seq: 10, get_clock
Sent 89 619.972019 619.971779 6: seq: 11, get_clock
Sent 90 620.956549 620.956309 6: seq: 12, get_clock
Sent 91 621.940829 621.940589 6: seq: 13, get_clock
Sent 92 622.925168 622.924928 6: seq: 14, get_clock
Sent 93 623.909361 623.909121 6: seq: 15, get_clock
Sent 94 624.893686 624.893446 6: seq: 16, get_clock
Sent 95 625.878518 625.878278 6: seq: 17, get_clock
Sent 96 626.863302 626.863062 6: seq: 18, get_clock
Sent 97 627.848377 627.848137 6: seq: 19, get_clock
Sent 98 628.833468 628.833228 6: seq: 1a, get_clock
Sent 99 628.914734 628.914494 6: seq: 1b, emergency_stop
Dumping receive queue 100 messages
Receive: 0 620.094910 619.972019 15: seq: 12, analog_in_state oid=18 next_clock=4037760000 value=13992
Receive: 1 620.114816 619.972019 15: seq: 12, analog_in_state oid=20 next_clock=4039200000 value=31357
Receive: 2 620.264893 619.972019 15: seq: 12, analog_in_state oid=15 next_clock=4050000000 value=31364
Receive: 3 620.394925 619.972019 15: seq: 12, analog_in_state oid=18 next_clock=4059360000 value=13992
Receive: 4 620.414839 619.972019 15: seq: 12, analog_in_state oid=20 next_clock=4060800000 value=31358
Receive: 5 620.564956 619.972019 15: seq: 12, analog_in_state oid=15 next_clock=4071600000 value=31342
Receive: 6 620.694933 619.972019 15: seq: 12, analog_in_state oid=18 next_clock=4080960000 value=13992
Receive: 7 620.714891 619.972019 15: seq: 12, analog_in_state oid=20 next_clock=4082400000 value=31357
Receive: 8 620.864971 619.972019 15: seq: 12, analog_in_state oid=15 next_clock=4093200000 value=31343
Receive: 9 620.959436 620.956549 11: seq: 13, clock clock=4078905608
Receive: 10 620.994943 620.956549 15: seq: 13, analog_in_state oid=18 next_clock=4102560000 value=13989
Receive: 11 621.014924 620.956549 15: seq: 13, analog_in_state oid=20 next_clock=4104000000 value=31357
Receive: 12 621.164973 620.956549 15: seq: 13, analog_in_state oid=15 next_clock=4114800000 value=31342
Receive: 13 621.294822 620.956549 15: seq: 13, analog_in_state oid=18 next_clock=4124160000 value=14007
Receive: 14 621.314988 620.956549 15: seq: 13, analog_in_state oid=20 next_clock=4125600000 value=31357
Receive: 15 621.464983 620.956549 15: seq: 13, analog_in_state oid=15 next_clock=4136400000 value=31344
Receive: 16 621.594850 620.956549 15: seq: 13, analog_in_state oid=18 next_clock=4145760000 value=13992
Receive: 17 621.614788 620.956549 15: seq: 13, analog_in_state oid=20 next_clock=4147200000 value=31353
Receive: 18 621.764866 620.956549 15: seq: 13, analog_in_state oid=15 next_clock=4158000000 value=31342
Receive: 19 621.894881 620.956549 15: seq: 13, analog_in_state oid=18 next_clock=4167360000 value=13993
Receive: 20 621.914828 620.956549 15: seq: 13, analog_in_state oid=20 next_clock=4168800000 value=31364
Receive: 21 621.943685 621.940829 11: seq: 14, clock clock=4149773408
Receive: 22 622.064893 621.940829 15: seq: 14, analog_in_state oid=15 next_clock=4179600000 value=31343
Receive: 23 622.194928 621.940829 15: seq: 14, analog_in_state oid=18 next_clock=4188960000 value=13994
Receive: 24 622.214872 621.940829 15: seq: 14, analog_in_state oid=20 next_clock=4190400000 value=31364
Receive: 25 622.364916 621.940829 15: seq: 14, analog_in_state oid=15 next_clock=4201200000 value=31343
Receive: 26 622.494917 621.940829 15: seq: 14, analog_in_state oid=18 next_clock=4210560000 value=13997
Receive: 27 622.514894 621.940829 15: seq: 14, analog_in_state oid=20 next_clock=4212000000 value=31357
Receive: 28 622.664918 621.940829 15: seq: 14, analog_in_state oid=15 next_clock=4222800000 value=31340
Receive: 29 622.794916 621.940829 14: seq: 14, analog_in_state oid=18 next_clock=4232160000 value=13991
Receive: 30 622.814980 621.940829 14: seq: 14, analog_in_state oid=20 next_clock=4233600000 value=31357
Receive: 31 622.928085 622.925168 11: seq: 15, clock clock=4220645436
Receive: 32 622.965003 622.925168 14: seq: 15, analog_in_state oid=15 next_clock=4244400000 value=31342
Receive: 33 623.094969 622.925168 14: seq: 15, analog_in_state oid=18 next_clock=4253760000 value=13994
Receive: 34 623.114928 622.925168 14: seq: 15, analog_in_state oid=20 next_clock=4255200000 value=31357
Receive: 35 623.264862 622.925168 14: seq: 15, analog_in_state oid=15 next_clock=4266000000 value=31364
Receive: 36 623.395011 622.925168 14: seq: 15, analog_in_state oid=18 next_clock=4275360000 value=13993
Receive: 37 623.414993 622.925168 14: seq: 15, analog_in_state oid=20 next_clock=4276800000 value=31357
Receive: 38 623.564902 622.925168 14: seq: 15, analog_in_state oid=15 next_clock=4287600000 value=31342
Receive: 39 623.694996 622.925168 14: seq: 15, analog_in_state oid=18 next_clock=1992704 value=13994
Receive: 40 623.714937 622.925168 14: seq: 15, analog_in_state oid=20 next_clock=3432704 value=31357
Receive: 41 623.864927 622.925168 14: seq: 15, analog_in_state oid=15 next_clock=14232704 value=31342
Receive: 42 623.912165 623.909361 10: seq: 16, clock clock=4291505844
Receive: 43 623.995018 623.909361 14: seq: 16, analog_in_state oid=18 next_clock=23592704 value=13997
Receive: 44 624.014986 623.909361 14: seq: 16, analog_in_state oid=20 next_clock=25032704 value=31358
Receive: 45 624.164947 623.909361 14: seq: 16, analog_in_state oid=15 next_clock=35832704 value=31343
Receive: 46 624.295077 623.909361 14: seq: 16, analog_in_state oid=18 next_clock=45192704 value=14011
Receive: 47 624.315052 623.909361 14: seq: 16, analog_in_state oid=20 next_clock=46632704 value=31357
Receive: 48 624.464964 623.909361 14: seq: 16, analog_in_state oid=15 next_clock=57432704 value=31343
Receive: 49 624.595324 623.909361 14: seq: 16, analog_in_state oid=18 next_clock=66792704 value=13991
Receive: 50 624.615096 623.909361 14: seq: 16, analog_in_state oid=20 next_clock=68232704 value=31353
Receive: 51 624.708182 623.909361 17: seq: 16, stats count=106 sum=2965900 sumsq=324434081
Receive: 52 624.764990 623.909361 14: seq: 16, analog_in_state oid=15 next_clock=79032704 value=31344
Receive: 53 624.896412 623.909361 14: seq: 16, analog_in_state oid=18 next_clock=88392704 value=13995
Receive: 54 624.896589 624.893686 10: seq: 17, clock clock=67408936
Receive: 55 624.915134 624.893686 14: seq: 17, analog_in_state oid=20 next_clock=89832704 value=31353
Receive: 56 625.065042 624.893686 14: seq: 17, analog_in_state oid=15 next_clock=100632704 value=31344
Receive: 57 625.194960 624.893686 14: seq: 17, analog_in_state oid=18 next_clock=109992704 value=13996
Receive: 58 625.214855 624.893686 14: seq: 17, analog_in_state oid=20 next_clock=111432704 value=31364
Receive: 59 625.364904 624.893686 14: seq: 17, analog_in_state oid=15 next_clock=122232704 value=31342
Receive: 60 625.494993 624.893686 14: seq: 17, analog_in_state oid=18 next_clock=131592704 value=13996
Receive: 61 625.514888 624.893686 14: seq: 17, analog_in_state oid=20 next_clock=133032704 value=31357
Receive: 62 625.664910 624.893686 14: seq: 17, analog_in_state oid=15 next_clock=143832704 value=31344
Receive: 63 625.795000 624.893686 14: seq: 17, analog_in_state oid=18 next_clock=153192704 value=13989
Receive: 64 625.814939 624.893686 14: seq: 17, analog_in_state oid=20 next_clock=154632704 value=31357
Receive: 65 625.881454 625.878518 10: seq: 18, clock clock=138319360
Receive: 66 625.964961 625.878518 14: seq: 18, analog_in_state oid=15 next_clock=165432704 value=31342
Receive: 67 626.095045 625.878518 14: seq: 18, analog_in_state oid=18 next_clock=174792704 value=13995
Receive: 68 626.114967 625.878518 14: seq: 18, analog_in_state oid=20 next_clock=176232704 value=31357
Receive: 69 626.264988 625.878518 14: seq: 18, analog_in_state oid=15 next_clock=187032704 value=31364
Receive: 70 626.395058 625.878518 14: seq: 18, analog_in_state oid=18 next_clock=196392704 value=13993
Receive: 71 626.415022 625.878518 14: seq: 18, analog_in_state oid=20 next_clock=197832704 value=31357
Receive: 72 626.564990 625.878518 15: seq: 18, analog_in_state oid=15 next_clock=208632704 value=31344
Receive: 73 626.695026 625.878518 15: seq: 18, analog_in_state oid=18 next_clock=217992704 value=13992
Receive: 74 626.714976 625.878518 15: seq: 18, analog_in_state oid=20 next_clock=219432704 value=31358
Receive: 75 626.866049 625.878518 15: seq: 18, analog_in_state oid=15 next_clock=230232704 value=31344
Receive: 76 626.866227 626.863302 11: seq: 19, clock clock=209219754
Receive: 77 626.995099 626.863302 15: seq: 19, analog_in_state oid=18 next_clock=239592704 value=13995
Receive: 78 627.015045 626.863302 15: seq: 19, analog_in_state oid=20 next_clock=241032704 value=31357
Receive: 79 627.165088 626.863302 15: seq: 19, analog_in_state oid=15 next_clock=251832704 value=31344
Receive: 80 627.295088 626.863302 15: seq: 19, analog_in_state oid=18 next_clock=261192704 value=14004
Receive: 81 627.315047 626.863302 15: seq: 19, analog_in_state oid=20 next_clock=262632704 value=31357
Receive: 82 627.465128 626.863302 15: seq: 19, analog_in_state oid=15 next_clock=273432704 value=31343
Receive: 83 627.595036 626.863302 15: seq: 19, analog_in_state oid=18 next_clock=282792704 value=13995
Receive: 84 627.615074 626.863302 15: seq: 19, analog_in_state oid=20 next_clock=284232704 value=31353
Receive: 85 627.765160 626.863302 15: seq: 19, analog_in_state oid=15 next_clock=295032704 value=31343
Receive: 86 627.851267 627.848377 11: seq: 1a, clock clock=280144528
Receive: 87 627.894955 627.848377 15: seq: 1a, analog_in_state oid=18 next_clock=304392704 value=13997
Receive: 88 627.914915 627.848377 15: seq: 1a, analog_in_state oid=20 next_clock=305832704 value=31353
Receive: 89 628.064945 627.848377 15: seq: 1a, analog_in_state oid=15 next_clock=316632704 value=31344
Receive: 90 628.194987 627.848377 15: seq: 1a, analog_in_state oid=18 next_clock=325992704 value=13994
Receive: 91 628.214952 627.848377 15: seq: 1a, analog_in_state oid=20 next_clock=327432704 value=31364
Receive: 92 628.364973 627.848377 15: seq: 1a, analog_in_state oid=15 next_clock=338232704 value=31343
Receive: 93 628.495038 627.848377 15: seq: 1a, analog_in_state oid=18 next_clock=347592704 value=13996
Receive: 94 628.514991 627.848377 15: seq: 1a, analog_in_state oid=20 next_clock=349032704 value=31358
Receive: 95 628.664994 627.848377 15: seq: 1a, analog_in_state oid=15 next_clock=359832704 value=31343
Receive: 96 628.795070 627.848377 15: seq: 1a, analog_in_state oid=18 next_clock=369192704 value=13994
Receive: 97 628.815014 627.848377 15: seq: 1a, analog_in_state oid=20 next_clock=370632704 value=31357
Receive: 98 628.836308 628.833468 11: seq: 1b, clock clock=351069644
Receive: 99 628.917736 628.914734 12: seq: 1c, shutdown clock=356921107 static_string_id=Command request

**Comment by proturka** [comment]
https://github.com/markniu/Bed_Distance_sensor/issues/7#issue-1609687260

same error happened to me also here, you can fix it with downgrading python version.
