### ISSUE TITLE
mks sgen l v1.0 can bd work?

### ISSUE THREAD

**Issue by Karolas123** [markniu/Bed_Distance_sensor#85]
Can I connect the bd sensor to the mks sgen l v1 board.  Which pin do you think I can use? Thank you for your help.

**Comment by Karolas123** [comment]
I think i can use SERVO0 SERVO1 p2.0 and p1.23 Can anyone confirm this?

**Comment by markniu** [comment]
right, you can use SERVO0 SERVO1

> I think i can use SERVO0 SERVO1 p2.0 and p1.23 Can anyone confirm this?

**Comment by Karolas123** [comment]
> right, you can use SERVO0 SERVO1
> 
> > I think i can use SERVO0 SERVO1 p2.0 and p1.23 Can anyone confirm this?

thx
