### ISSUE TITLE
 Internal error during connect: invalid syntax (BDsensor.py, line 1212)

### ISSUE THREAD

**Issue by LAZER555** [markniu/Bed_Distance_sensor#90]
Hi, after the last update i have this error. I reinstalled the sensor with the script, but didn't reflash the mcu

> Internal error during connect: invalid syntax (BDsensor.py, line 1212)
> 
> Once the underlying issue is corrected, use the "RESTART"
> command to reload the config and restart the host software.
> Printer is halted

**Comment by shlo-mix** [comment]
as a temporary solution, until mark will fix, you can open SSH file explorer and edit BDsensor.py under line 1212
![image](https://github.com/markniu/Bed_Distance_sensor/assets/156359888/6e0daca5-d5a6-4320-ade2-a8b8da121475)

change to:

![image](https://github.com/markniu/Bed_Distance_sensor/assets/156359888/cbf118c7-17f7-432c-8bcb-53e9e6b96e07)

**Comment by LAZER555** [comment]
Thanks it worked, fixed it with winscp :P All of this because of one Enter , haha

**Comment by markniu** [comment]
thanks! just fix that error by the last commit.
