### ISSUE TITLE
Cant flash new firmware

### ISSUE THREAD

**Issue by Mharasim1** [markniu/Bed_Distance_sensor#96]
im trying to flash new fimrware to my v1.1 BD senor and im always getting this error 
![bd](https://github.com/markniu/Bed_Distance_sensor/assets/89615269/5a2ecfb3-9069-4f46-9ac5-62d1a0b3e5cf)
i bought it in november last year its a v1.1 does it support collision sensing after update?

**Comment by markniu** [comment]
the v1.1 support collision sensing after flashing new firmware.
was there any more message before the "Re-hadshaking...successful"?
> im trying to flash new fimrware to my v1.1 BD senor and im always getting this error ![bd](https://private-user-images.githubusercontent.com/89615269/307686325-5a2ecfb3-9069-4f46-9ac5-62d1a0b3e5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzIzMjYsIm5iZiI6MTcwODkzMjAyNiwicGF0aCI6Ii84OTYxNTI2OS8zMDc2ODYzMjUtNWEyZWNmYjMtOTA2OS00ZjQ2LTlhYzUtNjJkMWEwYjNlNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA3MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NWQ2ZWQyYTliNTgwZWJkY2Q1MmMxOTExODZkYzcwOGI2ZDgyNzc0Y2NiOTQ3ZDcxNjlkNWI3ODYxODcwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K4mnrVOLC5j5BOF5nNqJhHNZfl41xbV4UsH3oLcUZqU) i bought it in november last year its a v1.1 does it support collision sensing after update?

**Comment by Mharasim1** [comment]
@markniu 
`Checking target MCU ... 
  MCU type: STC15W408AS
  F/W version: 7.2.5T

Current H/W Option:
  . Current system clock source is internal IRC oscillator
  . Current frequency: 30.047MHz
  . Oscillator gain is HIGH
  . Wakeup Timer frequency: 35.375KHz
  . Do not detect the level of P3.2 and P3.3 next download
  . Power-on reset, use the extra power-on delay
  . RESET pin behaves as IO pin
  . Reset while detect a Low-Voltage
  . Thresh voltage level of the built-in LVD : 2.83 V
  . Inhibit EEPROM operation under Low-Voltage  . CPU-Core supply level : 3.70 V
  . Hardware do not enable Watch-Dog-Timer
  . Watch-Dog-Timer pre-scalar : 256
  . Watch-Dog-Timer stop count in idle mode
  . Program can modify the Watch-Dog-Timer scalar
  . Do not erase user EEPROM area at next download
  . Do not control 485 at next download
  . Do not check user password next download
  . TXD is independent IO
  . TXD pin as quasi-bidirectional mode after reset
  . P2.0 output HIGH level after reset
  . Reference voltage: 1251 mV (Range: 1150~1320mV)
  . Testing time: 2023-9-20

  MCU type: STC15W408AS
  F/W version: 7.2.5T

Adjusting frequency ...			[1.000"]
Adjusted frequency: 30.035MHz (0.116%)

Re-handshaking ... Successful			[0.157"]
Current Baudrate: 115200
Erasing MCU flash ...  
Download failed ! (6.90D)(2024-02-26 07:34:59)
`

**Comment by Mharasim1** [comment]
I managed to flash it with lower baud rate

**Comment by 8bit-boom** [comment]
Hello, I trying to flash new firmware of STM32 version of bd sensor. In YouTube video there is some device that connect bd sensor and st-link, do I need similar device to flash it or can I flash using cable that's comes with bd sensor?

**Comment by markniu** [comment]
> Hello, I trying to flash new firmware of STM32 version of bd sensor. In YouTube video there is some device that connect bd sensor and st-link, do I need similar device to flash it or can I flash using cable that's comes with bd sensor?

Only the st-link can flash the STM32 version of bd sensor like the in the video, need to solder wires or with the burning fixture(1.27MM spacing,5Pin) like https://www.aliexpress.com/item/4001016694208.html?spm=a2g0o.productlist.main.21.5fca9446hdVqut&algo_pvid=00c04565-f627-47e8-a9a0-ad0f2e70a3f8&algo_exp_id=00c04565-f627-47e8-a9a0-ad0f2e70a3f8-10&pdp_npi=4%40dis%21USD%2112.68%2111.41%21%21%2112.68%2111.41%21%402167359c17094554238687816eba7d%2110000013519744505%21sea%21US%212656033920%21AB&curPageLogUid=g65NpMYIk6x8&utparam-url=scene%3Asearch%7Cquery_from%3A&gatewayAdapt=4itemAdapt

**Comment by Billy-d-Kidd** [comment]
I tried re-flashing the V1.1, and below is the results.
MCU type: STC15W408AS
  F/W version: 7.2.5T

Current H/W Option:
  . Current system clock source is internal IRC oscillator
  . Current frequency: 30.011MHz
  . Oscillator gain is HIGH
  . Wakeup Timer frequency: 35.575KHz
  . Do not detect the level of P3.2 and P3.3 next download
  . Power-on reset, use the extra power-on delay
  . RESET pin behaves as IO pin
  . Reset while detect a Low-Voltage
  . Thresh voltage level of the built-in LVD : 2.83 V
  . Inhibit EEPROM operation under Low-Voltage
  . CPU-Core supply level : 3.70 V
  . Hardware do not enable Watch-Dog-Timer
  . Watch-Dog-Timer pre-scalar : 256
  . Watch-Dog-Timer stop count in idle mode
  . Program can modify the Watch-Dog-Timer scalar
  . Do not erase user EEPROM area at next download
  . Do not control 485 at next download
  . Do not check user password next download
  . TXD is independent IO
  . TXD pin as quasi-bidirectional mode after reset
  . P2.0 output HIGH level after reset
  . Reference voltage: 1248 mV (Range: 1150~1320mV)
  . Testing time: 2023-5-19

  MCU type: STC15W408AS
  F/W version: 7.2.5T

Adjusting frequency ...			[1.141"]
Adjusted frequency: 30.005MHz (0.016%)

Re-handshaking ... Successful			[0.125"]
Current Baudrate: 115200
Erasing MCU flash ...  OK !		[0.531"]
Programming user code ... OK !		[1.750"]
Programming OPTIONS ... OK !		[0.047"]

H/W Option upgrade to:
  . Current system clock source is internal IRC oscillator
  . Current frequency: 30.005MHz
  . Oscillator gain is HIGH
  . Do not detect the level of P3.2 and P3.3 next download
  . Power-on reset, use the extra power-on delay
  . RESET pin behaves as IO pin
  . Reset while detect a Low-Voltage
  . Thresh voltage level of the built-in LVD : 2.83 V
  . Inhibit EEPROM operation under Low-Voltage
  . CPU-Core supply level : 3.70 V
  . Hardware do not enable Watch-Dog-Timer
  . Watch-Dog-Timer pre-scalar : 256
  . Watch-Dog-Timer stop count in idle mode
  . Program can modify the Watch-Dog-Timer scalar
  . Do not erase user EEPROM area at next download
  . Do not control 485 at next download
  . Do not check user password next download
  . TXD is independent IO
  . TXD pin as quasi-bidirectional mode after reset
  . P2.0 output HIGH level after reset
  . Reference voltage: 1248 mV (Range: 1150~1320mV)
  . Testing time: 2023-5-19
MCU ID : F51FC4F323A9EE

  MCU type: STC15W408AS
  F/W version: 7.2.5T

  . Set frequency: 30.000MHz
  . Adjusted frequency: 30.005MHz 
  . Trim error: 0.016%
  Complete !(2024-03-12 06:55:23)

I am still unable to get a connection, and no matter which M102 s-X I use I get the 1024 error. 
I did execute a homing command after issuing the "SET_KINEMATIC_POSITION Z=50". Moved the Z axis -20, and the nozzle made contact with the bed and stopped.

**Comment by markniu** [comment]
you can check again the download hex file. https://github.com/markniu/Bed_Distance_sensor/issues/74#issuecomment-1931326433

> I tried re-flashing the V1.1, and below is the results. MCU type: STC15W408AS F/W version: 7.2.5T
>

**Comment by Billy-d-Kidd** [comment]
Re-downloaded the repo as a zip, tried re-flashing the hex file, STC showed same as previously.
Still 'No data from BDsensor,please check connection' on M102 S-1 command.
Sensor LED triggers when testing it.
I am using Creality 4.2.7 with sda_pin: PB1 & scl_pin: PB0.
I have the 5 port probe connector connected via the cable that came with a 3d touch cable to BDsensor.
It worked like this prior to flashing for collison sensing.

**Comment by markniu** [comment]
after flashing, there should be some data message from the serial port of bdsensor, also with version text string at the start. 

![image](https://github.com/markniu/Bed_Distance_sensor/assets/13879340/88e7d9f4-bbc1-4890-997f-9c8addd3fb1c)

**Comment by Billy-d-Kidd** [comment]
Here is the results.
![stc-isp-v6 19K-a](https://github.com/markniu/Bed_Distance_sensor/assets/99415467/7d601d0f-5823-46fd-b041-4838cf55d7fa)

**Comment by markniu** [comment]
Hello @Billy-d-Kidd ,  sorry for I forgot this for a long time.  if the bdsensor cannot work after reflash, please send me your order number or shipping address, I would like to send you the latest version. 

> Here is the results.

**Comment by Billy-d-Kidd** [comment]
Sorry about the length of time it took to respond, been out on vacation.
I re-ordered the sensor before I left, and you handled this by email.
Once again thank you!
