### ISSUE TITLE
Bed distance sensor on SB2040

### ISSUE THREAD

**Issue by emessage** [markniu/Bed_Distance_sensor#97]
Has anyone had success using the sensor with an sb2040 v2?  I've tried connecting clk to gpio28 and SDA to gpio289 but when I execute m102 s-1 it says that the sensor is not connected.  I've even tried connecting clk to pwm0 and gpio25 with no success.  But connecting the pins to my skr 3eZ bltouch pins works fine.

**Comment by markniu** [comment]
unfortunately, there are capacitors on the gpio28 29 25 , that 100nf capacitor can filter the communication signal. 
![image](https://github.com/markniu/Bed_Distance_sensor/assets/13879340/b9d3c71a-c49f-4f70-a042-5dc9197f3b59)

**Comment by emessage** [comment]
> unfortunately, there are capacitors on the gpio28 29 25 , that 100nf capacitor can filter the communication signal. ![image](https://private-user-images.githubusercontent.com/13879340/308019511-b9d3c71a-c49f-4f70-a042-5dc9197f3b59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzAzNTEsIm5iZiI6MTcwOTAzMDA1MSwicGF0aCI6Ii8xMzg3OTM0MC8zMDgwMTk1MTEtYjlkM2M3MWEtYzQ5Zi00ZjcwLWEwNDItNWRjOTE5N2YzYjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEwMzQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNDU3NjQxMTA5MmFhNDRhZjYwMTA5MWYxYTI4NTNmYzA4OWFlYTgzOTRjNDg4MTU2Y2I0YjhiNWY3OWFkYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QKYcJi-0jWJHtByDL1wj7mmPXiIyGVLjThGvQJ0nWxU)

Ok thanks for the info.  That really sucks.
